// Code generated by go-swagger; DO NOT EDIT.

package team_contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// CreateNewTeamContactReader is a Reader for the CreateNewTeamContact structure.
type CreateNewTeamContactReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNewTeamContactReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateNewTeamContactOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateNewTeamContactBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateNewTeamContactForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateNewTeamContactNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateNewTeamContactUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateNewTeamContactInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /teams/{teamID}/contacts] create-new-team-contact", response, response.Code())
	}
}

// NewCreateNewTeamContactOK creates a CreateNewTeamContactOK with default headers values
func NewCreateNewTeamContactOK() *CreateNewTeamContactOK {
	return &CreateNewTeamContactOK{}
}

/*
CreateNewTeamContactOK describes a response with status code 200, with default header values.

Team contact created successfully
*/
type CreateNewTeamContactOK struct {
	Payload *models.DtoContact
}

// IsSuccess returns true when this create new team contact o k response has a 2xx status code
func (o *CreateNewTeamContactOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create new team contact o k response has a 3xx status code
func (o *CreateNewTeamContactOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new team contact o k response has a 4xx status code
func (o *CreateNewTeamContactOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new team contact o k response has a 5xx status code
func (o *CreateNewTeamContactOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create new team contact o k response a status code equal to that given
func (o *CreateNewTeamContactOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create new team contact o k response
func (o *CreateNewTeamContactOK) Code() int {
	return 200
}

func (o *CreateNewTeamContactOK) Error() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactOK  %+v", 200, o.Payload)
}

func (o *CreateNewTeamContactOK) String() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactOK  %+v", 200, o.Payload)
}

func (o *CreateNewTeamContactOK) GetPayload() *models.DtoContact {
	return o.Payload
}

func (o *CreateNewTeamContactOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoContact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewTeamContactBadRequest creates a CreateNewTeamContactBadRequest with default headers values
func NewCreateNewTeamContactBadRequest() *CreateNewTeamContactBadRequest {
	return &CreateNewTeamContactBadRequest{}
}

/*
CreateNewTeamContactBadRequest describes a response with status code 400, with default header values.

Bad request from client
*/
type CreateNewTeamContactBadRequest struct {
	Payload *models.APIErrorInvalidRequestExample
}

// IsSuccess returns true when this create new team contact bad request response has a 2xx status code
func (o *CreateNewTeamContactBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new team contact bad request response has a 3xx status code
func (o *CreateNewTeamContactBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new team contact bad request response has a 4xx status code
func (o *CreateNewTeamContactBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new team contact bad request response has a 5xx status code
func (o *CreateNewTeamContactBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create new team contact bad request response a status code equal to that given
func (o *CreateNewTeamContactBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create new team contact bad request response
func (o *CreateNewTeamContactBadRequest) Code() int {
	return 400
}

func (o *CreateNewTeamContactBadRequest) Error() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactBadRequest  %+v", 400, o.Payload)
}

func (o *CreateNewTeamContactBadRequest) String() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactBadRequest  %+v", 400, o.Payload)
}

func (o *CreateNewTeamContactBadRequest) GetPayload() *models.APIErrorInvalidRequestExample {
	return o.Payload
}

func (o *CreateNewTeamContactBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInvalidRequestExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewTeamContactForbidden creates a CreateNewTeamContactForbidden with default headers values
func NewCreateNewTeamContactForbidden() *CreateNewTeamContactForbidden {
	return &CreateNewTeamContactForbidden{}
}

/*
CreateNewTeamContactForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateNewTeamContactForbidden struct {
	Payload *models.APIErrorForbiddenExample
}

// IsSuccess returns true when this create new team contact forbidden response has a 2xx status code
func (o *CreateNewTeamContactForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new team contact forbidden response has a 3xx status code
func (o *CreateNewTeamContactForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new team contact forbidden response has a 4xx status code
func (o *CreateNewTeamContactForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new team contact forbidden response has a 5xx status code
func (o *CreateNewTeamContactForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create new team contact forbidden response a status code equal to that given
func (o *CreateNewTeamContactForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create new team contact forbidden response
func (o *CreateNewTeamContactForbidden) Code() int {
	return 403
}

func (o *CreateNewTeamContactForbidden) Error() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactForbidden  %+v", 403, o.Payload)
}

func (o *CreateNewTeamContactForbidden) String() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactForbidden  %+v", 403, o.Payload)
}

func (o *CreateNewTeamContactForbidden) GetPayload() *models.APIErrorForbiddenExample {
	return o.Payload
}

func (o *CreateNewTeamContactForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorForbiddenExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewTeamContactNotFound creates a CreateNewTeamContactNotFound with default headers values
func NewCreateNewTeamContactNotFound() *CreateNewTeamContactNotFound {
	return &CreateNewTeamContactNotFound{}
}

/*
CreateNewTeamContactNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type CreateNewTeamContactNotFound struct {
	Payload *models.APIErrorNotFoundExample
}

// IsSuccess returns true when this create new team contact not found response has a 2xx status code
func (o *CreateNewTeamContactNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new team contact not found response has a 3xx status code
func (o *CreateNewTeamContactNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new team contact not found response has a 4xx status code
func (o *CreateNewTeamContactNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new team contact not found response has a 5xx status code
func (o *CreateNewTeamContactNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create new team contact not found response a status code equal to that given
func (o *CreateNewTeamContactNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create new team contact not found response
func (o *CreateNewTeamContactNotFound) Code() int {
	return 404
}

func (o *CreateNewTeamContactNotFound) Error() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactNotFound  %+v", 404, o.Payload)
}

func (o *CreateNewTeamContactNotFound) String() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactNotFound  %+v", 404, o.Payload)
}

func (o *CreateNewTeamContactNotFound) GetPayload() *models.APIErrorNotFoundExample {
	return o.Payload
}

func (o *CreateNewTeamContactNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorNotFoundExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewTeamContactUnprocessableEntity creates a CreateNewTeamContactUnprocessableEntity with default headers values
func NewCreateNewTeamContactUnprocessableEntity() *CreateNewTeamContactUnprocessableEntity {
	return &CreateNewTeamContactUnprocessableEntity{}
}

/*
CreateNewTeamContactUnprocessableEntity describes a response with status code 422, with default header values.

Render error
*/
type CreateNewTeamContactUnprocessableEntity struct {
	Payload *models.APIErrorRenderExample
}

// IsSuccess returns true when this create new team contact unprocessable entity response has a 2xx status code
func (o *CreateNewTeamContactUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new team contact unprocessable entity response has a 3xx status code
func (o *CreateNewTeamContactUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new team contact unprocessable entity response has a 4xx status code
func (o *CreateNewTeamContactUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create new team contact unprocessable entity response has a 5xx status code
func (o *CreateNewTeamContactUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create new team contact unprocessable entity response a status code equal to that given
func (o *CreateNewTeamContactUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create new team contact unprocessable entity response
func (o *CreateNewTeamContactUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateNewTeamContactUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateNewTeamContactUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateNewTeamContactUnprocessableEntity) GetPayload() *models.APIErrorRenderExample {
	return o.Payload
}

func (o *CreateNewTeamContactUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorRenderExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateNewTeamContactInternalServerError creates a CreateNewTeamContactInternalServerError with default headers values
func NewCreateNewTeamContactInternalServerError() *CreateNewTeamContactInternalServerError {
	return &CreateNewTeamContactInternalServerError{}
}

/*
CreateNewTeamContactInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type CreateNewTeamContactInternalServerError struct {
	Payload *models.APIErrorInternalServerExample
}

// IsSuccess returns true when this create new team contact internal server error response has a 2xx status code
func (o *CreateNewTeamContactInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create new team contact internal server error response has a 3xx status code
func (o *CreateNewTeamContactInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create new team contact internal server error response has a 4xx status code
func (o *CreateNewTeamContactInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create new team contact internal server error response has a 5xx status code
func (o *CreateNewTeamContactInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create new team contact internal server error response a status code equal to that given
func (o *CreateNewTeamContactInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create new team contact internal server error response
func (o *CreateNewTeamContactInternalServerError) Code() int {
	return 500
}

func (o *CreateNewTeamContactInternalServerError) Error() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateNewTeamContactInternalServerError) String() string {
	return fmt.Sprintf("[POST /teams/{teamID}/contacts][%d] createNewTeamContactInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateNewTeamContactInternalServerError) GetPayload() *models.APIErrorInternalServerExample {
	return o.Payload
}

func (o *CreateNewTeamContactInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInternalServerExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
