/*
 * Moira Alert
 *
 * This is an API description for [Moira Alert API](https://moira.readthedocs.io/en/latest/overview.html) Check us out on [Github](https://github.com/moira-alert) or look up our [guide](https://moira.readthedocs.io) on getting started with Moira
 *
 * API version: master
 * Contact: opensource@skbkontur.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MoiraTriggerCheck struct {
	AloneMetrics map[string]bool `json:"alone_metrics,omitempty"`
	CreatedAt int64 `json:"created_at,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	Desc string `json:"desc,omitempty"`
	ErrorValue float64 `json:"error_value,omitempty"`
	Expression string `json:"expression,omitempty"`
	Highlights map[string]string `json:"highlights,omitempty"`
	Id string `json:"id,omitempty"`
	IsRemote bool `json:"is_remote,omitempty"`
	LastCheck *MoiraCheckData `json:"last_check,omitempty"`
	MuteNewMetrics bool `json:"mute_new_metrics,omitempty"`
	Name string `json:"name,omitempty"`
	Patterns []string `json:"patterns,omitempty"`
	PythonExpression string `json:"python_expression,omitempty"`
	Sched *MoiraScheduleData `json:"sched,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Targets []string `json:"targets,omitempty"`
	Throttling int64 `json:"throttling,omitempty"`
	TriggerType string `json:"trigger_type,omitempty"`
	Ttl int64 `json:"ttl,omitempty"`
	TtlState string `json:"ttl_state,omitempty"`
	UpdatedAt int64 `json:"updated_at,omitempty"`
	UpdatedBy string `json:"updated_by,omitempty"`
	WarnValue float64 `json:"warn_value,omitempty"`
}
