// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DtoNotifierState dto notifier state
//
// swagger:model dto.NotifierState
type DtoNotifierState struct {

	// actor
	// Example: AUTO
	// Required: true
	Actor *string `json:"actor"`

	// message
	// Example: Moira has been turned off for maintenance
	Message string `json:"message,omitempty"`

	// state
	// Example: ERROR
	// Required: true
	State *string `json:"state"`
}

// Validate validates this dto notifier state
func (m *DtoNotifierState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoNotifierState) validateActor(formats strfmt.Registry) error {

	if err := validate.Required("actor", "body", m.Actor); err != nil {
		return err
	}

	return nil
}

func (m *DtoNotifierState) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dto notifier state based on context it is used
func (m *DtoNotifierState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoNotifierState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoNotifierState) UnmarshalBinary(b []byte) error {
	var res DtoNotifierState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
