// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DtoContact dto contact
//
// swagger:model dto.Contact
type DtoContact struct {

	// extra message
	ExtraMessage string `json:"extra_message,omitempty"`

	// id
	// Example: 1dd38765-c5be-418d-81fa-7a5f879c2315
	// Required: true
	ID *string `json:"id"`

	// name
	// Example: Mail Alerts
	Name string `json:"name,omitempty"`

	// team id
	TeamID string `json:"team_id,omitempty"`

	// type
	// Example: mail
	// Required: true
	Type *string `json:"type"`

	// user
	User string `json:"user,omitempty"`

	// value
	// Example: devops@example.com
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this dto contact
func (m *DtoContact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoContact) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *DtoContact) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *DtoContact) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dto contact based on context it is used
func (m *DtoContact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoContact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoContact) UnmarshalBinary(b []byte) error {
	var res DtoContact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
