// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DtoTriggerModel dto trigger model
//
// swagger:model dto.TriggerModel
type DtoTriggerModel struct {

	// A list of targets that have only alone metrics
	// Example: {"t1":true}
	// Required: true
	AloneMetrics map[string]bool `json:"alone_metrics"`

	// Shows the exact cluster from where the metrics are fetched
	// Example: default
	// Required: true
	ClusterID *string `json:"cluster_id"`

	// Datetime when the trigger was created
	// Required: true
	CreatedAt *string `json:"created_at"`

	// Username who created trigger
	// Required: true
	CreatedBy *string `json:"created_by"`

	// Description string
	// Example: check the size of /var/log
	Desc *string `json:"desc,omitempty"`

	// ERROR threshold
	// Example: 1000
	// Required: true
	ErrorValue *float64 `json:"error_value"`

	// Used if you need more complex logic than provided by WARN/ERROR values
	// Required: true
	Expression *string `json:"expression"`

	// Trigger unique ID
	// Example: 292516ed-4924-4154-a62c-ebe312431fce
	// Required: true
	ID *string `json:"id"`

	// Shows if trigger is remote (graphite-backend) based or stored inside Moira-Redis DB
	//
	// Deprecated: Use TriggerSource field instead
	// Example: false
	// Required: true
	IsRemote *bool `json:"is_remote"`

	// If true, first event NODATA → OK will be omitted
	// Example: false
	// Required: true
	MuteNewMetrics *bool `json:"mute_new_metrics"`

	// Trigger name
	// Example: Not enough disk space left
	// Required: true
	Name *string `json:"name"`

	// Graphite patterns for trigger
	// Example: [""]
	// Required: true
	Patterns []string `json:"patterns"`

	// Determines when Moira should monitor trigger
	Sched struct {
		MoiraScheduleData
	} `json:"sched,omitempty"`

	// Set of tags to manipulate subscriptions
	// Example: ["server","disk"]
	// Required: true
	Tags []string `json:"tags"`

	// Graphite-like targets: t1, t2, ...
	// Example: ["devOps.my_server.hdd.freespace_mbytes"]
	// Required: true
	Targets []string `json:"targets"`

	// Shows the type of source from where the metrics are fetched
	// Example: graphite_local
	// Required: true
	TriggerSource *string `json:"trigger_source"`

	// Could be: rising, falling, expression
	// Example: rising
	// Required: true
	TriggerType *string `json:"trigger_type"`

	// When there are no metrics for trigger, Moira will switch metric to TTLState state after TTL seconds
	// Example: 600
	TTL int64 `json:"ttl,omitempty"`

	// When there are no metrics for trigger, Moira will switch metric to TTLState state after TTL seconds
	// Example: NODATA
	TTLState *string `json:"ttl_state,omitempty"`

	// Datetime  when the trigger was updated
	// Required: true
	UpdatedAt *string `json:"updated_at"`

	// Username who updated trigger
	// Required: true
	UpdatedBy *string `json:"updated_by"`

	// WARN threshold
	// Example: 500
	// Required: true
	WarnValue *float64 `json:"warn_value"`
}

// Validate validates this dto trigger model
func (m *DtoTriggerModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAloneMetrics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClusterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrorValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpression(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIsRemote(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMuteNewMetrics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePatterns(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSched(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargets(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTriggerSource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTriggerType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWarnValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoTriggerModel) validateAloneMetrics(formats strfmt.Registry) error {

	if err := validate.Required("alone_metrics", "body", m.AloneMetrics); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateClusterID(formats strfmt.Registry) error {

	if err := validate.Required("cluster_id", "body", m.ClusterID); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateCreatedBy(formats strfmt.Registry) error {

	if err := validate.Required("created_by", "body", m.CreatedBy); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateErrorValue(formats strfmt.Registry) error {

	if err := validate.Required("error_value", "body", m.ErrorValue); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateExpression(formats strfmt.Registry) error {

	if err := validate.Required("expression", "body", m.Expression); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateIsRemote(formats strfmt.Registry) error {

	if err := validate.Required("is_remote", "body", m.IsRemote); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateMuteNewMetrics(formats strfmt.Registry) error {

	if err := validate.Required("mute_new_metrics", "body", m.MuteNewMetrics); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validatePatterns(formats strfmt.Registry) error {

	if err := validate.Required("patterns", "body", m.Patterns); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateSched(formats strfmt.Registry) error {
	if swag.IsZero(m.Sched) { // not required
		return nil
	}

	return nil
}

func (m *DtoTriggerModel) validateTags(formats strfmt.Registry) error {

	if err := validate.Required("tags", "body", m.Tags); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateTargets(formats strfmt.Registry) error {

	if err := validate.Required("targets", "body", m.Targets); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateTriggerSource(formats strfmt.Registry) error {

	if err := validate.Required("trigger_source", "body", m.TriggerSource); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateTriggerType(formats strfmt.Registry) error {

	if err := validate.Required("trigger_type", "body", m.TriggerType); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updated_at", "body", m.UpdatedAt); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateUpdatedBy(formats strfmt.Registry) error {

	if err := validate.Required("updated_by", "body", m.UpdatedBy); err != nil {
		return err
	}

	return nil
}

func (m *DtoTriggerModel) validateWarnValue(formats strfmt.Registry) error {

	if err := validate.Required("warn_value", "body", m.WarnValue); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this dto trigger model based on the context it is used
func (m *DtoTriggerModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSched(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoTriggerModel) contextValidateSched(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *DtoTriggerModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoTriggerModel) UnmarshalBinary(b []byte) error {
	var res DtoTriggerModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
