// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MoiraNotificationEvent moira notification event
//
// swagger:model moira.NotificationEvent
type MoiraNotificationEvent struct {

	// contact id
	ContactID string `json:"contact_id,omitempty"`

	// event message
	// Required: true
	EventMessage struct {
		MoiraEventInfo
	} `json:"event_message"`

	// metric
	// Example: carbon.agents.*.metricsReceived
	// Required: true
	Metric *string `json:"metric"`

	// msg
	Msg *string `json:"msg,omitempty"`

	// old state
	// Example: ERROR
	// Required: true
	OldState *string `json:"old_state"`

	// state
	// Example: OK
	// Required: true
	State *string `json:"state"`

	// sub id
	SubID *string `json:"sub_id,omitempty"`

	// timestamp
	// Example: 1590741878
	// Required: true
	Timestamp *int64 `json:"timestamp"`

	// trigger event
	// Example: true
	TriggerEvent bool `json:"trigger_event,omitempty"`

	// trigger id
	// Example: 5ff37996-8927-4cab-8987-970e80d8e0a8
	// Required: true
	TriggerID *string `json:"trigger_id"`

	// value
	// Example: 70
	Value *float64 `json:"value,omitempty"`

	// values
	Values map[string]float64 `json:"values,omitempty"`
}

// Validate validates this moira notification event
func (m *MoiraNotificationEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetric(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOldState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTriggerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MoiraNotificationEvent) validateEventMessage(formats strfmt.Registry) error {

	return nil
}

func (m *MoiraNotificationEvent) validateMetric(formats strfmt.Registry) error {

	if err := validate.Required("metric", "body", m.Metric); err != nil {
		return err
	}

	return nil
}

func (m *MoiraNotificationEvent) validateOldState(formats strfmt.Registry) error {

	if err := validate.Required("old_state", "body", m.OldState); err != nil {
		return err
	}

	return nil
}

func (m *MoiraNotificationEvent) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

func (m *MoiraNotificationEvent) validateTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("timestamp", "body", m.Timestamp); err != nil {
		return err
	}

	return nil
}

func (m *MoiraNotificationEvent) validateTriggerID(formats strfmt.Registry) error {

	if err := validate.Required("trigger_id", "body", m.TriggerID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this moira notification event based on the context it is used
func (m *MoiraNotificationEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEventMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MoiraNotificationEvent) contextValidateEventMessage(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *MoiraNotificationEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MoiraNotificationEvent) UnmarshalBinary(b []byte) error {
	var res MoiraNotificationEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
