// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MoiraPlottingData moira plotting data
//
// swagger:model moira.PlottingData
type MoiraPlottingData struct {

	// enabled
	// Example: true
	Enabled bool `json:"enabled,omitempty"`

	// theme
	// Example: dark
	Theme string `json:"theme,omitempty"`
}

// Validate validates this moira plotting data
func (m *MoiraPlottingData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this moira plotting data based on context it is used
func (m *MoiraPlottingData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MoiraPlottingData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MoiraPlottingData) UnmarshalBinary(b []byte) error {
	var res MoiraPlottingData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
