// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MoiraTrigger moira trigger
//
// swagger:model moira.Trigger
type MoiraTrigger struct {

	// alone metrics
	// Example: {"t1":true}
	AloneMetrics map[string]bool `json:"alone_metrics,omitempty"`

	// created at
	CreatedAt *int64 `json:"created_at,omitempty"`

	// created by
	CreatedBy string `json:"created_by,omitempty"`

	// desc
	// Example: check the size of /var/log
	Desc *string `json:"desc,omitempty"`

	// error value
	// Example: 1000
	ErrorValue *float64 `json:"error_value,omitempty"`

	// expression
	Expression *string `json:"expression,omitempty"`

	// id
	// Example: 292516ed-4924-4154-a62c-ebe312431fce
	ID string `json:"id,omitempty"`

	// mute new metrics
	// Example: false
	MuteNewMetrics bool `json:"mute_new_metrics,omitempty"`

	// name
	// Example: Not enough disk space left
	Name string `json:"name,omitempty"`

	// patterns
	// Example: [""]
	Patterns []string `json:"patterns"`

	// python expression
	PythonExpression *string `json:"python_expression,omitempty"`

	// sched
	Sched struct {
		MoiraScheduleData
	} `json:"sched,omitempty"`

	// tags
	// Example: ["server","disk"]
	Tags []string `json:"tags"`

	// targets
	// Example: ["devOps.my_server.hdd.freespace_mbytes"]
	Targets []string `json:"targets"`

	// trigger source
	// Example: graphite_local
	TriggerSource struct {
		MoiraTriggerSource
	} `json:"trigger_source,omitempty"`

	// trigger type
	// Example: rising
	TriggerType string `json:"trigger_type,omitempty"`

	// ttl
	// Example: 600
	TTL int64 `json:"ttl,omitempty"`

	// ttl state
	// Example: NODATA
	TTLState *string `json:"ttl_state,omitempty"`

	// updated at
	UpdatedAt *int64 `json:"updated_at,omitempty"`

	// updated by
	UpdatedBy string `json:"updated_by,omitempty"`

	// warn value
	// Example: 5000
	WarnValue *float64 `json:"warn_value,omitempty"`
}

// Validate validates this moira trigger
func (m *MoiraTrigger) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSched(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTriggerSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MoiraTrigger) validateSched(formats strfmt.Registry) error {
	if swag.IsZero(m.Sched) { // not required
		return nil
	}

	return nil
}

func (m *MoiraTrigger) validateTriggerSource(formats strfmt.Registry) error {
	if swag.IsZero(m.TriggerSource) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this moira trigger based on the context it is used
func (m *MoiraTrigger) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSched(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTriggerSource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MoiraTrigger) contextValidateSched(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *MoiraTrigger) contextValidateTriggerSource(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *MoiraTrigger) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MoiraTrigger) UnmarshalBinary(b []byte) error {
	var res MoiraTrigger
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
