// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetEventsListParams creates a new GetEventsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEventsListParams() *GetEventsListParams {
	return &GetEventsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEventsListParamsWithTimeout creates a new GetEventsListParams object
// with the ability to set a timeout on a request.
func NewGetEventsListParamsWithTimeout(timeout time.Duration) *GetEventsListParams {
	return &GetEventsListParams{
		timeout: timeout,
	}
}

// NewGetEventsListParamsWithContext creates a new GetEventsListParams object
// with the ability to set a context for a request.
func NewGetEventsListParamsWithContext(ctx context.Context) *GetEventsListParams {
	return &GetEventsListParams{
		Context: ctx,
	}
}

// NewGetEventsListParamsWithHTTPClient creates a new GetEventsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEventsListParamsWithHTTPClient(client *http.Client) *GetEventsListParams {
	return &GetEventsListParams{
		HTTPClient: client,
	}
}

/*
GetEventsListParams contains all the parameters to send to the API endpoint

	for the get events list operation.

	Typically these are written to a http.Request.
*/
type GetEventsListParams struct {

	/* From.

	   Start time of the time range

	   Default: "-3hours"
	*/
	From *string

	/* Metric.

	   Regular expression that will be used to filter events

	   Default: ".*"
	*/
	Metric *string

	/* P.

	   Defines the number of the displayed page. E.g, p=2 would display the 2nd page
	*/
	P *int64

	/* Size.

	   Number of items to be displayed on one page. if size = -1 then all events returned

	   Default: 100
	*/
	Size *int64

	/* States.

	   String of ',' separated state names. If empty then all states will be used.
	*/
	States []string

	/* To.

	   End time of the time range

	   Default: "now"
	*/
	To *string

	/* TriggerID.

	   The ID of updated trigger

	   Default: "bcba82f5-48cf-44c0-b7d6-e1d32c64a88c"
	*/
	TriggerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get events list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventsListParams) WithDefaults() *GetEventsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get events list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEventsListParams) SetDefaults() {
	var (
		fromDefault = string("-3hours")

		metricDefault = string(".*")

		pDefault = int64(0)

		sizeDefault = int64(100)

		toDefault = string("now")

		triggerIDDefault = string("bcba82f5-48cf-44c0-b7d6-e1d32c64a88c")
	)

	val := GetEventsListParams{
		From:      &fromDefault,
		Metric:    &metricDefault,
		P:         &pDefault,
		Size:      &sizeDefault,
		To:        &toDefault,
		TriggerID: triggerIDDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get events list params
func (o *GetEventsListParams) WithTimeout(timeout time.Duration) *GetEventsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get events list params
func (o *GetEventsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get events list params
func (o *GetEventsListParams) WithContext(ctx context.Context) *GetEventsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get events list params
func (o *GetEventsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get events list params
func (o *GetEventsListParams) WithHTTPClient(client *http.Client) *GetEventsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get events list params
func (o *GetEventsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the get events list params
func (o *GetEventsListParams) WithFrom(from *string) *GetEventsListParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get events list params
func (o *GetEventsListParams) SetFrom(from *string) {
	o.From = from
}

// WithMetric adds the metric to the get events list params
func (o *GetEventsListParams) WithMetric(metric *string) *GetEventsListParams {
	o.SetMetric(metric)
	return o
}

// SetMetric adds the metric to the get events list params
func (o *GetEventsListParams) SetMetric(metric *string) {
	o.Metric = metric
}

// WithP adds the p to the get events list params
func (o *GetEventsListParams) WithP(p *int64) *GetEventsListParams {
	o.SetP(p)
	return o
}

// SetP adds the p to the get events list params
func (o *GetEventsListParams) SetP(p *int64) {
	o.P = p
}

// WithSize adds the size to the get events list params
func (o *GetEventsListParams) WithSize(size *int64) *GetEventsListParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the get events list params
func (o *GetEventsListParams) SetSize(size *int64) {
	o.Size = size
}

// WithStates adds the states to the get events list params
func (o *GetEventsListParams) WithStates(states []string) *GetEventsListParams {
	o.SetStates(states)
	return o
}

// SetStates adds the states to the get events list params
func (o *GetEventsListParams) SetStates(states []string) {
	o.States = states
}

// WithTo adds the to to the get events list params
func (o *GetEventsListParams) WithTo(to *string) *GetEventsListParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get events list params
func (o *GetEventsListParams) SetTo(to *string) {
	o.To = to
}

// WithTriggerID adds the triggerID to the get events list params
func (o *GetEventsListParams) WithTriggerID(triggerID string) *GetEventsListParams {
	o.SetTriggerID(triggerID)
	return o
}

// SetTriggerID adds the triggerId to the get events list params
func (o *GetEventsListParams) SetTriggerID(triggerID string) {
	o.TriggerID = triggerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.Metric != nil {

		// query param metric
		var qrMetric string

		if o.Metric != nil {
			qrMetric = *o.Metric
		}
		qMetric := qrMetric
		if qMetric != "" {

			if err := r.SetQueryParam("metric", qMetric); err != nil {
				return err
			}
		}
	}

	if o.P != nil {

		// query param p
		var qrP int64

		if o.P != nil {
			qrP = *o.P
		}
		qP := swag.FormatInt64(qrP)
		if qP != "" {

			if err := r.SetQueryParam("p", qP); err != nil {
				return err
			}
		}
	}

	if o.Size != nil {

		// query param size
		var qrSize int64

		if o.Size != nil {
			qrSize = *o.Size
		}
		qSize := swag.FormatInt64(qrSize)
		if qSize != "" {

			if err := r.SetQueryParam("size", qSize); err != nil {
				return err
			}
		}
	}

	if o.States != nil {

		// binding items for states
		joinedStates := o.bindParamStates(reg)

		// query array param states
		if err := r.SetQueryParam("states", joinedStates...); err != nil {
			return err
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	// path param triggerID
	if err := r.SetPathParam("triggerID", o.TriggerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetEventsList binds the parameter states
func (o *GetEventsListParams) bindParamStates(formats strfmt.Registry) []string {
	statesIR := o.States

	var statesIC []string
	for _, statesIIR := range statesIR { // explode []string

		statesIIV := statesIIR // string as string
		statesIC = append(statesIC, statesIIV)
	}

	// items.CollectionFormat: "csv"
	statesIS := swag.JoinByFormat(statesIC, "csv")

	return statesIS
}
