/*
Moira Alert

Testing TeamContactAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pkg

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_pkg_TeamContactAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TeamContactAPIService CreateNewTeamContact", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var teamID string

		resp, httpRes, err := apiClient.TeamContactAPI.CreateNewTeamContact(context.Background(), teamID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
