/*
Moira Alert

Testing TriggerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pkg

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_pkg_TriggerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TriggerAPIService CreateTrigger", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.CreateTrigger(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService DeletePager", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.DeletePager(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService DeleteTriggerMetric", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.DeleteTriggerMetric(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService DeleteTriggerNodataMetrics", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.DeleteTriggerNodataMetrics(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService DeleteTriggerThrottling", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		httpRes, err := apiClient.TriggerAPI.DeleteTriggerThrottling(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetAllTriggers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.GetAllTriggers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetTrigger", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.GetTrigger(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetTriggerDump", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.GetTriggerDump(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetTriggerMetrics", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.GetTriggerMetrics(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetTriggerState", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.GetTriggerState(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetTriggerThrottling", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.GetTriggerThrottling(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetTriggersNoisiness", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.GetTriggersNoisiness(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService GetUnusedTriggers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.GetUnusedTriggers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService RemoveTrigger", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		httpRes, err := apiClient.TriggerAPI.RemoveTrigger(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService RenderTriggerMetrics", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.RenderTriggerMetrics(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService SearchTriggers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.SearchTriggers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService SetTriggerMaintenance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.SetTriggerMaintenance(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService TriggerCheck", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.TriggerAPI.TriggerCheck(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TriggerAPIService UpdateTrigger", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var triggerID string

		resp, httpRes, err := apiClient.TriggerAPI.UpdateTrigger(context.Background(), triggerID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
