// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTeamUserParams creates a new DeleteTeamUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTeamUserParams() *DeleteTeamUserParams {
	return &DeleteTeamUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTeamUserParamsWithTimeout creates a new DeleteTeamUserParams object
// with the ability to set a timeout on a request.
func NewDeleteTeamUserParamsWithTimeout(timeout time.Duration) *DeleteTeamUserParams {
	return &DeleteTeamUserParams{
		timeout: timeout,
	}
}

// NewDeleteTeamUserParamsWithContext creates a new DeleteTeamUserParams object
// with the ability to set a context for a request.
func NewDeleteTeamUserParamsWithContext(ctx context.Context) *DeleteTeamUserParams {
	return &DeleteTeamUserParams{
		Context: ctx,
	}
}

// NewDeleteTeamUserParamsWithHTTPClient creates a new DeleteTeamUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTeamUserParamsWithHTTPClient(client *http.Client) *DeleteTeamUserParams {
	return &DeleteTeamUserParams{
		HTTPClient: client,
	}
}

/*
DeleteTeamUserParams contains all the parameters to send to the API endpoint

	for the delete team user operation.

	Typically these are written to a http.Request.
*/
type DeleteTeamUserParams struct {

	/* TeamID.

	   ID of the team

	   Default: "bcba82f5-48cf-44c0-b7d6-e1d32c64a88c"
	*/
	TeamID string

	/* TeamUserID.

	   User login in methods related to teams manipulation

	   Default: "anonymous"
	*/
	TeamUserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete team user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTeamUserParams) WithDefaults() *DeleteTeamUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete team user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTeamUserParams) SetDefaults() {
	var (
		teamIDDefault = string("bcba82f5-48cf-44c0-b7d6-e1d32c64a88c")

		teamUserIDDefault = string("anonymous")
	)

	val := DeleteTeamUserParams{
		TeamID:     teamIDDefault,
		TeamUserID: teamUserIDDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete team user params
func (o *DeleteTeamUserParams) WithTimeout(timeout time.Duration) *DeleteTeamUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete team user params
func (o *DeleteTeamUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete team user params
func (o *DeleteTeamUserParams) WithContext(ctx context.Context) *DeleteTeamUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete team user params
func (o *DeleteTeamUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete team user params
func (o *DeleteTeamUserParams) WithHTTPClient(client *http.Client) *DeleteTeamUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete team user params
func (o *DeleteTeamUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the delete team user params
func (o *DeleteTeamUserParams) WithTeamID(teamID string) *DeleteTeamUserParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the delete team user params
func (o *DeleteTeamUserParams) SetTeamID(teamID string) {
	o.TeamID = teamID
}

// WithTeamUserID adds the teamUserID to the delete team user params
func (o *DeleteTeamUserParams) WithTeamUserID(teamUserID string) *DeleteTeamUserParams {
	o.SetTeamUserID(teamUserID)
	return o
}

// SetTeamUserID adds the teamUserId to the delete team user params
func (o *DeleteTeamUserParams) SetTeamUserID(teamUserID string) {
	o.TeamUserID = teamUserID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTeamUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param teamID
	if err := r.SetPathParam("teamID", o.TeamID); err != nil {
		return err
	}

	// path param teamUserID
	if err := r.SetPathParam("teamUserID", o.TeamUserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
