// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllTeamsParams creates a new GetAllTeamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllTeamsParams() *GetAllTeamsParams {
	return &GetAllTeamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllTeamsParamsWithTimeout creates a new GetAllTeamsParams object
// with the ability to set a timeout on a request.
func NewGetAllTeamsParamsWithTimeout(timeout time.Duration) *GetAllTeamsParams {
	return &GetAllTeamsParams{
		timeout: timeout,
	}
}

// NewGetAllTeamsParamsWithContext creates a new GetAllTeamsParams object
// with the ability to set a context for a request.
func NewGetAllTeamsParamsWithContext(ctx context.Context) *GetAllTeamsParams {
	return &GetAllTeamsParams{
		Context: ctx,
	}
}

// NewGetAllTeamsParamsWithHTTPClient creates a new GetAllTeamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllTeamsParamsWithHTTPClient(client *http.Client) *GetAllTeamsParams {
	return &GetAllTeamsParams{
		HTTPClient: client,
	}
}

/*
GetAllTeamsParams contains all the parameters to send to the API endpoint

	for the get all teams operation.

	Typically these are written to a http.Request.
*/
type GetAllTeamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all teams params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTeamsParams) WithDefaults() *GetAllTeamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all teams params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTeamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all teams params
func (o *GetAllTeamsParams) WithTimeout(timeout time.Duration) *GetAllTeamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all teams params
func (o *GetAllTeamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all teams params
func (o *GetAllTeamsParams) WithContext(ctx context.Context) *GetAllTeamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all teams params
func (o *GetAllTeamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all teams params
func (o *GetAllTeamsParams) WithHTTPClient(client *http.Client) *GetAllTeamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all teams params
func (o *GetAllTeamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllTeamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
