// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTeamSettingsParams creates a new GetTeamSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTeamSettingsParams() *GetTeamSettingsParams {
	return &GetTeamSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTeamSettingsParamsWithTimeout creates a new GetTeamSettingsParams object
// with the ability to set a timeout on a request.
func NewGetTeamSettingsParamsWithTimeout(timeout time.Duration) *GetTeamSettingsParams {
	return &GetTeamSettingsParams{
		timeout: timeout,
	}
}

// NewGetTeamSettingsParamsWithContext creates a new GetTeamSettingsParams object
// with the ability to set a context for a request.
func NewGetTeamSettingsParamsWithContext(ctx context.Context) *GetTeamSettingsParams {
	return &GetTeamSettingsParams{
		Context: ctx,
	}
}

// NewGetTeamSettingsParamsWithHTTPClient creates a new GetTeamSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTeamSettingsParamsWithHTTPClient(client *http.Client) *GetTeamSettingsParams {
	return &GetTeamSettingsParams{
		HTTPClient: client,
	}
}

/*
GetTeamSettingsParams contains all the parameters to send to the API endpoint

	for the get team settings operation.

	Typically these are written to a http.Request.
*/
type GetTeamSettingsParams struct {

	/* TeamID.

	   ID of the team

	   Default: "bcba82f5-48cf-44c0-b7d6-e1d32c64a88c"
	*/
	TeamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get team settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeamSettingsParams) WithDefaults() *GetTeamSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get team settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTeamSettingsParams) SetDefaults() {
	var (
		teamIDDefault = string("bcba82f5-48cf-44c0-b7d6-e1d32c64a88c")
	)

	val := GetTeamSettingsParams{
		TeamID: teamIDDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get team settings params
func (o *GetTeamSettingsParams) WithTimeout(timeout time.Duration) *GetTeamSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get team settings params
func (o *GetTeamSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get team settings params
func (o *GetTeamSettingsParams) WithContext(ctx context.Context) *GetTeamSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get team settings params
func (o *GetTeamSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get team settings params
func (o *GetTeamSettingsParams) WithHTTPClient(client *http.Client) *GetTeamSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get team settings params
func (o *GetTeamSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeamID adds the teamID to the get team settings params
func (o *GetTeamSettingsParams) WithTeamID(teamID string) *GetTeamSettingsParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the get team settings params
func (o *GetTeamSettingsParams) SetTeamID(teamID string) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTeamSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param teamID
	if err := r.SetPathParam("teamID", o.TeamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
