// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// GetNotifierStateForSourcesReader is a Reader for the GetNotifierStateForSources structure.
type GetNotifierStateForSourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNotifierStateForSourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNotifierStateForSourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewGetNotifierStateForSourcesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNotifierStateForSourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /health/notifier] get-notifier-state-for-sources", response, response.Code())
	}
}

// NewGetNotifierStateForSourcesOK creates a GetNotifierStateForSourcesOK with default headers values
func NewGetNotifierStateForSourcesOK() *GetNotifierStateForSourcesOK {
	return &GetNotifierStateForSourcesOK{}
}

/*
GetNotifierStateForSourcesOK describes a response with status code 200, with default header values.

Notifier state retrieved
*/
type GetNotifierStateForSourcesOK struct {
	Payload *models.DtoNotifierStatesForSources
}

// IsSuccess returns true when this get notifier state for sources o k response has a 2xx status code
func (o *GetNotifierStateForSourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get notifier state for sources o k response has a 3xx status code
func (o *GetNotifierStateForSourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notifier state for sources o k response has a 4xx status code
func (o *GetNotifierStateForSourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get notifier state for sources o k response has a 5xx status code
func (o *GetNotifierStateForSourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get notifier state for sources o k response a status code equal to that given
func (o *GetNotifierStateForSourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get notifier state for sources o k response
func (o *GetNotifierStateForSourcesOK) Code() int {
	return 200
}

func (o *GetNotifierStateForSourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/notifier][%d] getNotifierStateForSourcesOK %s", 200, payload)
}

func (o *GetNotifierStateForSourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/notifier][%d] getNotifierStateForSourcesOK %s", 200, payload)
}

func (o *GetNotifierStateForSourcesOK) GetPayload() *models.DtoNotifierStatesForSources {
	return o.Payload
}

func (o *GetNotifierStateForSourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoNotifierStatesForSources)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNotifierStateForSourcesUnprocessableEntity creates a GetNotifierStateForSourcesUnprocessableEntity with default headers values
func NewGetNotifierStateForSourcesUnprocessableEntity() *GetNotifierStateForSourcesUnprocessableEntity {
	return &GetNotifierStateForSourcesUnprocessableEntity{}
}

/*
GetNotifierStateForSourcesUnprocessableEntity describes a response with status code 422, with default header values.

Render error
*/
type GetNotifierStateForSourcesUnprocessableEntity struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this get notifier state for sources unprocessable entity response has a 2xx status code
func (o *GetNotifierStateForSourcesUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get notifier state for sources unprocessable entity response has a 3xx status code
func (o *GetNotifierStateForSourcesUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notifier state for sources unprocessable entity response has a 4xx status code
func (o *GetNotifierStateForSourcesUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get notifier state for sources unprocessable entity response has a 5xx status code
func (o *GetNotifierStateForSourcesUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get notifier state for sources unprocessable entity response a status code equal to that given
func (o *GetNotifierStateForSourcesUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get notifier state for sources unprocessable entity response
func (o *GetNotifierStateForSourcesUnprocessableEntity) Code() int {
	return 422
}

func (o *GetNotifierStateForSourcesUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/notifier][%d] getNotifierStateForSourcesUnprocessableEntity %s", 422, payload)
}

func (o *GetNotifierStateForSourcesUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/notifier][%d] getNotifierStateForSourcesUnprocessableEntity %s", 422, payload)
}

func (o *GetNotifierStateForSourcesUnprocessableEntity) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetNotifierStateForSourcesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNotifierStateForSourcesInternalServerError creates a GetNotifierStateForSourcesInternalServerError with default headers values
func NewGetNotifierStateForSourcesInternalServerError() *GetNotifierStateForSourcesInternalServerError {
	return &GetNotifierStateForSourcesInternalServerError{}
}

/*
GetNotifierStateForSourcesInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetNotifierStateForSourcesInternalServerError struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this get notifier state for sources internal server error response has a 2xx status code
func (o *GetNotifierStateForSourcesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get notifier state for sources internal server error response has a 3xx status code
func (o *GetNotifierStateForSourcesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get notifier state for sources internal server error response has a 4xx status code
func (o *GetNotifierStateForSourcesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get notifier state for sources internal server error response has a 5xx status code
func (o *GetNotifierStateForSourcesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get notifier state for sources internal server error response a status code equal to that given
func (o *GetNotifierStateForSourcesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get notifier state for sources internal server error response
func (o *GetNotifierStateForSourcesInternalServerError) Code() int {
	return 500
}

func (o *GetNotifierStateForSourcesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/notifier][%d] getNotifierStateForSourcesInternalServerError %s", 500, payload)
}

func (o *GetNotifierStateForSourcesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /health/notifier][%d] getNotifierStateForSourcesInternalServerError %s", 500, payload)
}

func (o *GetNotifierStateForSourcesInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetNotifierStateForSourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
