// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserSubscriptionsParams creates a new GetUserSubscriptionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserSubscriptionsParams() *GetUserSubscriptionsParams {
	return &GetUserSubscriptionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserSubscriptionsParamsWithTimeout creates a new GetUserSubscriptionsParams object
// with the ability to set a timeout on a request.
func NewGetUserSubscriptionsParamsWithTimeout(timeout time.Duration) *GetUserSubscriptionsParams {
	return &GetUserSubscriptionsParams{
		timeout: timeout,
	}
}

// NewGetUserSubscriptionsParamsWithContext creates a new GetUserSubscriptionsParams object
// with the ability to set a context for a request.
func NewGetUserSubscriptionsParamsWithContext(ctx context.Context) *GetUserSubscriptionsParams {
	return &GetUserSubscriptionsParams{
		Context: ctx,
	}
}

// NewGetUserSubscriptionsParamsWithHTTPClient creates a new GetUserSubscriptionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserSubscriptionsParamsWithHTTPClient(client *http.Client) *GetUserSubscriptionsParams {
	return &GetUserSubscriptionsParams{
		HTTPClient: client,
	}
}

/*
GetUserSubscriptionsParams contains all the parameters to send to the API endpoint

	for the get user subscriptions operation.

	Typically these are written to a http.Request.
*/
type GetUserSubscriptionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user subscriptions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSubscriptionsParams) WithDefaults() *GetUserSubscriptionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user subscriptions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSubscriptionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user subscriptions params
func (o *GetUserSubscriptionsParams) WithTimeout(timeout time.Duration) *GetUserSubscriptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user subscriptions params
func (o *GetUserSubscriptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user subscriptions params
func (o *GetUserSubscriptionsParams) WithContext(ctx context.Context) *GetUserSubscriptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user subscriptions params
func (o *GetUserSubscriptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user subscriptions params
func (o *GetUserSubscriptionsParams) WithHTTPClient(client *http.Client) *GetUserSubscriptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user subscriptions params
func (o *GetUserSubscriptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserSubscriptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
