// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// GetUserSubscriptionsReader is a Reader for the GetUserSubscriptions structure.
type GetUserSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserSubscriptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewGetUserSubscriptionsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetUserSubscriptionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /subscription] get-user-subscriptions", response, response.Code())
	}
}

// NewGetUserSubscriptionsOK creates a GetUserSubscriptionsOK with default headers values
func NewGetUserSubscriptionsOK() *GetUserSubscriptionsOK {
	return &GetUserSubscriptionsOK{}
}

/*
GetUserSubscriptionsOK describes a response with status code 200, with default header values.

Subscriptions fetched successfully
*/
type GetUserSubscriptionsOK struct {
	Payload *models.DtoSubscriptionList
}

// IsSuccess returns true when this get user subscriptions o k response has a 2xx status code
func (o *GetUserSubscriptionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get user subscriptions o k response has a 3xx status code
func (o *GetUserSubscriptionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user subscriptions o k response has a 4xx status code
func (o *GetUserSubscriptionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user subscriptions o k response has a 5xx status code
func (o *GetUserSubscriptionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get user subscriptions o k response a status code equal to that given
func (o *GetUserSubscriptionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get user subscriptions o k response
func (o *GetUserSubscriptionsOK) Code() int {
	return 200
}

func (o *GetUserSubscriptionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscription][%d] getUserSubscriptionsOK %s", 200, payload)
}

func (o *GetUserSubscriptionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscription][%d] getUserSubscriptionsOK %s", 200, payload)
}

func (o *GetUserSubscriptionsOK) GetPayload() *models.DtoSubscriptionList {
	return o.Payload
}

func (o *GetUserSubscriptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoSubscriptionList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserSubscriptionsUnprocessableEntity creates a GetUserSubscriptionsUnprocessableEntity with default headers values
func NewGetUserSubscriptionsUnprocessableEntity() *GetUserSubscriptionsUnprocessableEntity {
	return &GetUserSubscriptionsUnprocessableEntity{}
}

/*
GetUserSubscriptionsUnprocessableEntity describes a response with status code 422, with default header values.

Render error
*/
type GetUserSubscriptionsUnprocessableEntity struct {
	Payload *models.APIErrorRenderExample
}

// IsSuccess returns true when this get user subscriptions unprocessable entity response has a 2xx status code
func (o *GetUserSubscriptionsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user subscriptions unprocessable entity response has a 3xx status code
func (o *GetUserSubscriptionsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user subscriptions unprocessable entity response has a 4xx status code
func (o *GetUserSubscriptionsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get user subscriptions unprocessable entity response has a 5xx status code
func (o *GetUserSubscriptionsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get user subscriptions unprocessable entity response a status code equal to that given
func (o *GetUserSubscriptionsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get user subscriptions unprocessable entity response
func (o *GetUserSubscriptionsUnprocessableEntity) Code() int {
	return 422
}

func (o *GetUserSubscriptionsUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscription][%d] getUserSubscriptionsUnprocessableEntity %s", 422, payload)
}

func (o *GetUserSubscriptionsUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscription][%d] getUserSubscriptionsUnprocessableEntity %s", 422, payload)
}

func (o *GetUserSubscriptionsUnprocessableEntity) GetPayload() *models.APIErrorRenderExample {
	return o.Payload
}

func (o *GetUserSubscriptionsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorRenderExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserSubscriptionsInternalServerError creates a GetUserSubscriptionsInternalServerError with default headers values
func NewGetUserSubscriptionsInternalServerError() *GetUserSubscriptionsInternalServerError {
	return &GetUserSubscriptionsInternalServerError{}
}

/*
GetUserSubscriptionsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetUserSubscriptionsInternalServerError struct {
	Payload *models.APIErrorInternalServerExample
}

// IsSuccess returns true when this get user subscriptions internal server error response has a 2xx status code
func (o *GetUserSubscriptionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user subscriptions internal server error response has a 3xx status code
func (o *GetUserSubscriptionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user subscriptions internal server error response has a 4xx status code
func (o *GetUserSubscriptionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user subscriptions internal server error response has a 5xx status code
func (o *GetUserSubscriptionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get user subscriptions internal server error response a status code equal to that given
func (o *GetUserSubscriptionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get user subscriptions internal server error response
func (o *GetUserSubscriptionsInternalServerError) Code() int {
	return 500
}

func (o *GetUserSubscriptionsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscription][%d] getUserSubscriptionsInternalServerError %s", 500, payload)
}

func (o *GetUserSubscriptionsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscription][%d] getUserSubscriptionsInternalServerError %s", 500, payload)
}

func (o *GetUserSubscriptionsInternalServerError) GetPayload() *models.APIErrorInternalServerExample {
	return o.Payload
}

func (o *GetUserSubscriptionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInternalServerExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
