// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// GetContactByIDReader is a Reader for the GetContactByID structure.
type GetContactByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContactByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContactByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetContactByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetContactByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetContactByIDUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetContactByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /contact/{contactID}] get-contact-by-id", response, response.Code())
	}
}

// NewGetContactByIDOK creates a GetContactByIDOK with default headers values
func NewGetContactByIDOK() *GetContactByIDOK {
	return &GetContactByIDOK{}
}

/*
GetContactByIDOK describes a response with status code 200, with default header values.

Successfully received contact
*/
type GetContactByIDOK struct {
	Payload *models.DtoContact
}

// IsSuccess returns true when this get contact by Id o k response has a 2xx status code
func (o *GetContactByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get contact by Id o k response has a 3xx status code
func (o *GetContactByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get contact by Id o k response has a 4xx status code
func (o *GetContactByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get contact by Id o k response has a 5xx status code
func (o *GetContactByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get contact by Id o k response a status code equal to that given
func (o *GetContactByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get contact by Id o k response
func (o *GetContactByIDOK) Code() int {
	return 200
}

func (o *GetContactByIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdOK %s", 200, payload)
}

func (o *GetContactByIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdOK %s", 200, payload)
}

func (o *GetContactByIDOK) GetPayload() *models.DtoContact {
	return o.Payload
}

func (o *GetContactByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoContact)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactByIDForbidden creates a GetContactByIDForbidden with default headers values
func NewGetContactByIDForbidden() *GetContactByIDForbidden {
	return &GetContactByIDForbidden{}
}

/*
GetContactByIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetContactByIDForbidden struct {
	Payload *models.APIErrorForbiddenExample
}

// IsSuccess returns true when this get contact by Id forbidden response has a 2xx status code
func (o *GetContactByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get contact by Id forbidden response has a 3xx status code
func (o *GetContactByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get contact by Id forbidden response has a 4xx status code
func (o *GetContactByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get contact by Id forbidden response has a 5xx status code
func (o *GetContactByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get contact by Id forbidden response a status code equal to that given
func (o *GetContactByIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get contact by Id forbidden response
func (o *GetContactByIDForbidden) Code() int {
	return 403
}

func (o *GetContactByIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdForbidden %s", 403, payload)
}

func (o *GetContactByIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdForbidden %s", 403, payload)
}

func (o *GetContactByIDForbidden) GetPayload() *models.APIErrorForbiddenExample {
	return o.Payload
}

func (o *GetContactByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorForbiddenExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactByIDNotFound creates a GetContactByIDNotFound with default headers values
func NewGetContactByIDNotFound() *GetContactByIDNotFound {
	return &GetContactByIDNotFound{}
}

/*
GetContactByIDNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type GetContactByIDNotFound struct {
	Payload *models.APIErrorNotFoundExample
}

// IsSuccess returns true when this get contact by Id not found response has a 2xx status code
func (o *GetContactByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get contact by Id not found response has a 3xx status code
func (o *GetContactByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get contact by Id not found response has a 4xx status code
func (o *GetContactByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get contact by Id not found response has a 5xx status code
func (o *GetContactByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get contact by Id not found response a status code equal to that given
func (o *GetContactByIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get contact by Id not found response
func (o *GetContactByIDNotFound) Code() int {
	return 404
}

func (o *GetContactByIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdNotFound %s", 404, payload)
}

func (o *GetContactByIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdNotFound %s", 404, payload)
}

func (o *GetContactByIDNotFound) GetPayload() *models.APIErrorNotFoundExample {
	return o.Payload
}

func (o *GetContactByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorNotFoundExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactByIDUnprocessableEntity creates a GetContactByIDUnprocessableEntity with default headers values
func NewGetContactByIDUnprocessableEntity() *GetContactByIDUnprocessableEntity {
	return &GetContactByIDUnprocessableEntity{}
}

/*
GetContactByIDUnprocessableEntity describes a response with status code 422, with default header values.

Render error
*/
type GetContactByIDUnprocessableEntity struct {
	Payload *models.APIErrorRenderExample
}

// IsSuccess returns true when this get contact by Id unprocessable entity response has a 2xx status code
func (o *GetContactByIDUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get contact by Id unprocessable entity response has a 3xx status code
func (o *GetContactByIDUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get contact by Id unprocessable entity response has a 4xx status code
func (o *GetContactByIDUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get contact by Id unprocessable entity response has a 5xx status code
func (o *GetContactByIDUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get contact by Id unprocessable entity response a status code equal to that given
func (o *GetContactByIDUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get contact by Id unprocessable entity response
func (o *GetContactByIDUnprocessableEntity) Code() int {
	return 422
}

func (o *GetContactByIDUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdUnprocessableEntity %s", 422, payload)
}

func (o *GetContactByIDUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdUnprocessableEntity %s", 422, payload)
}

func (o *GetContactByIDUnprocessableEntity) GetPayload() *models.APIErrorRenderExample {
	return o.Payload
}

func (o *GetContactByIDUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorRenderExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactByIDInternalServerError creates a GetContactByIDInternalServerError with default headers values
func NewGetContactByIDInternalServerError() *GetContactByIDInternalServerError {
	return &GetContactByIDInternalServerError{}
}

/*
GetContactByIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetContactByIDInternalServerError struct {
	Payload *models.APIErrorInternalServerExample
}

// IsSuccess returns true when this get contact by Id internal server error response has a 2xx status code
func (o *GetContactByIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get contact by Id internal server error response has a 3xx status code
func (o *GetContactByIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get contact by Id internal server error response has a 4xx status code
func (o *GetContactByIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get contact by Id internal server error response has a 5xx status code
func (o *GetContactByIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get contact by Id internal server error response a status code equal to that given
func (o *GetContactByIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get contact by Id internal server error response
func (o *GetContactByIDInternalServerError) Code() int {
	return 500
}

func (o *GetContactByIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdInternalServerError %s", 500, payload)
}

func (o *GetContactByIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /contact/{contactID}][%d] getContactByIdInternalServerError %s", 500, payload)
}

func (o *GetContactByIDInternalServerError) GetPayload() *models.APIErrorInternalServerExample {
	return o.Payload
}

func (o *GetContactByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInternalServerExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
