// Code generated by go-swagger; DO NOT EDIT.

package pattern

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// DeletePatternReader is a Reader for the DeletePattern structure.
type DeletePatternReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePatternReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePatternOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeletePatternBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeletePatternInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /pattern/{pattern}] delete-pattern", response, response.Code())
	}
}

// NewDeletePatternOK creates a DeletePatternOK with default headers values
func NewDeletePatternOK() *DeletePatternOK {
	return &DeletePatternOK{}
}

/*
DeletePatternOK describes a response with status code 200, with default header values.

Pattern deleted successfully
*/
type DeletePatternOK struct {
}

// IsSuccess returns true when this delete pattern o k response has a 2xx status code
func (o *DeletePatternOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete pattern o k response has a 3xx status code
func (o *DeletePatternOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete pattern o k response has a 4xx status code
func (o *DeletePatternOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete pattern o k response has a 5xx status code
func (o *DeletePatternOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete pattern o k response a status code equal to that given
func (o *DeletePatternOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete pattern o k response
func (o *DeletePatternOK) Code() int {
	return 200
}

func (o *DeletePatternOK) Error() string {
	return fmt.Sprintf("[DELETE /pattern/{pattern}][%d] deletePatternOK ", 200)
}

func (o *DeletePatternOK) String() string {
	return fmt.Sprintf("[DELETE /pattern/{pattern}][%d] deletePatternOK ", 200)
}

func (o *DeletePatternOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePatternBadRequest creates a DeletePatternBadRequest with default headers values
func NewDeletePatternBadRequest() *DeletePatternBadRequest {
	return &DeletePatternBadRequest{}
}

/*
DeletePatternBadRequest describes a response with status code 400, with default header values.

Bad request from client
*/
type DeletePatternBadRequest struct {
	Payload *models.APIErrorInvalidRequestExample
}

// IsSuccess returns true when this delete pattern bad request response has a 2xx status code
func (o *DeletePatternBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete pattern bad request response has a 3xx status code
func (o *DeletePatternBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete pattern bad request response has a 4xx status code
func (o *DeletePatternBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete pattern bad request response has a 5xx status code
func (o *DeletePatternBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete pattern bad request response a status code equal to that given
func (o *DeletePatternBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete pattern bad request response
func (o *DeletePatternBadRequest) Code() int {
	return 400
}

func (o *DeletePatternBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /pattern/{pattern}][%d] deletePatternBadRequest  %+v", 400, o.Payload)
}

func (o *DeletePatternBadRequest) String() string {
	return fmt.Sprintf("[DELETE /pattern/{pattern}][%d] deletePatternBadRequest  %+v", 400, o.Payload)
}

func (o *DeletePatternBadRequest) GetPayload() *models.APIErrorInvalidRequestExample {
	return o.Payload
}

func (o *DeletePatternBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInvalidRequestExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePatternInternalServerError creates a DeletePatternInternalServerError with default headers values
func NewDeletePatternInternalServerError() *DeletePatternInternalServerError {
	return &DeletePatternInternalServerError{}
}

/*
DeletePatternInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeletePatternInternalServerError struct {
	Payload *models.APIErrorInternalServerExample
}

// IsSuccess returns true when this delete pattern internal server error response has a 2xx status code
func (o *DeletePatternInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete pattern internal server error response has a 3xx status code
func (o *DeletePatternInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete pattern internal server error response has a 4xx status code
func (o *DeletePatternInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete pattern internal server error response has a 5xx status code
func (o *DeletePatternInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete pattern internal server error response a status code equal to that given
func (o *DeletePatternInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete pattern internal server error response
func (o *DeletePatternInternalServerError) Code() int {
	return 500
}

func (o *DeletePatternInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /pattern/{pattern}][%d] deletePatternInternalServerError  %+v", 500, o.Payload)
}

func (o *DeletePatternInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /pattern/{pattern}][%d] deletePatternInternalServerError  %+v", 500, o.Payload)
}

func (o *DeletePatternInternalServerError) GetPayload() *models.APIErrorInternalServerExample {
	return o.Payload
}

func (o *DeletePatternInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInternalServerExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
