/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the DtoContactNoisiness type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoContactNoisiness{}

// DtoContactNoisiness struct for DtoContactNoisiness
type DtoContactNoisiness struct {
	// EventsCount for the contact.
	EventsCount *int32  `json:"events_count,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	TeamId      *string `json:"team_id,omitempty"`
	Type        *string `json:"type,omitempty"`
	User        *string `json:"user,omitempty"`
	Value       *string `json:"value,omitempty"`
}

// NewDtoContactNoisiness instantiates a new DtoContactNoisiness object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoContactNoisiness() *DtoContactNoisiness {
	this := DtoContactNoisiness{}
	return &this
}

// NewDtoContactNoisinessWithDefaults instantiates a new DtoContactNoisiness object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoContactNoisinessWithDefaults() *DtoContactNoisiness {
	this := DtoContactNoisiness{}
	return &this
}

// GetEventsCount returns the EventsCount field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetEventsCount() int32 {
	if o == nil || IsNil(o.EventsCount) {
		var ret int32
		return ret
	}
	return *o.EventsCount
}

// GetEventsCountOk returns a tuple with the EventsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetEventsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EventsCount) {
		return nil, false
	}
	return o.EventsCount, true
}

// HasEventsCount returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasEventsCount() bool {
	if o != nil && !IsNil(o.EventsCount) {
		return true
	}

	return false
}

// SetEventsCount gets a reference to the given int32 and assigns it to the EventsCount field.
func (o *DtoContactNoisiness) SetEventsCount(v int32) {
	o.EventsCount = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoContactNoisiness) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoContactNoisiness) SetName(v string) {
	o.Name = &v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetTeamId() string {
	if o == nil || IsNil(o.TeamId) {
		var ret string
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetTeamIdOk() (*string, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given string and assigns it to the TeamId field.
func (o *DtoContactNoisiness) SetTeamId(v string) {
	o.TeamId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DtoContactNoisiness) SetType(v string) {
	o.Type = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *DtoContactNoisiness) SetUser(v string) {
	o.User = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DtoContactNoisiness) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoContactNoisiness) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DtoContactNoisiness) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DtoContactNoisiness) SetValue(v string) {
	o.Value = &v
}

func (o DtoContactNoisiness) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoContactNoisiness) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventsCount) {
		toSerialize["events_count"] = o.EventsCount
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TeamId) {
		toSerialize["team_id"] = o.TeamId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableDtoContactNoisiness struct {
	value *DtoContactNoisiness
	isSet bool
}

func (v NullableDtoContactNoisiness) Get() *DtoContactNoisiness {
	return v.value
}

func (v *NullableDtoContactNoisiness) Set(val *DtoContactNoisiness) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoContactNoisiness) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoContactNoisiness) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoContactNoisiness(val *DtoContactNoisiness) *NullableDtoContactNoisiness {
	return &NullableDtoContactNoisiness{value: val, isSet: true}
}

func (v NullableDtoContactNoisiness) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoContactNoisiness) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
