/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the DtoTeamSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoTeamSettings{}

// DtoTeamSettings struct for DtoTeamSettings
type DtoTeamSettings struct {
	Contacts      []DtoTeamContact        `json:"contacts,omitempty"`
	Subscriptions []MoiraSubscriptionData `json:"subscriptions,omitempty"`
	TeamId        *string                 `json:"team_id,omitempty"`
}

// NewDtoTeamSettings instantiates a new DtoTeamSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoTeamSettings() *DtoTeamSettings {
	this := DtoTeamSettings{}
	return &this
}

// NewDtoTeamSettingsWithDefaults instantiates a new DtoTeamSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoTeamSettingsWithDefaults() *DtoTeamSettings {
	this := DtoTeamSettings{}
	return &this
}

// GetContacts returns the Contacts field value if set, zero value otherwise.
func (o *DtoTeamSettings) GetContacts() []DtoTeamContact {
	if o == nil || IsNil(o.Contacts) {
		var ret []DtoTeamContact
		return ret
	}
	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTeamSettings) GetContactsOk() ([]DtoTeamContact, bool) {
	if o == nil || IsNil(o.Contacts) {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *DtoTeamSettings) HasContacts() bool {
	if o != nil && !IsNil(o.Contacts) {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []DtoTeamContact and assigns it to the Contacts field.
func (o *DtoTeamSettings) SetContacts(v []DtoTeamContact) {
	o.Contacts = v
}

// GetSubscriptions returns the Subscriptions field value if set, zero value otherwise.
func (o *DtoTeamSettings) GetSubscriptions() []MoiraSubscriptionData {
	if o == nil || IsNil(o.Subscriptions) {
		var ret []MoiraSubscriptionData
		return ret
	}
	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTeamSettings) GetSubscriptionsOk() ([]MoiraSubscriptionData, bool) {
	if o == nil || IsNil(o.Subscriptions) {
		return nil, false
	}
	return o.Subscriptions, true
}

// HasSubscriptions returns a boolean if a field has been set.
func (o *DtoTeamSettings) HasSubscriptions() bool {
	if o != nil && !IsNil(o.Subscriptions) {
		return true
	}

	return false
}

// SetSubscriptions gets a reference to the given []MoiraSubscriptionData and assigns it to the Subscriptions field.
func (o *DtoTeamSettings) SetSubscriptions(v []MoiraSubscriptionData) {
	o.Subscriptions = v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *DtoTeamSettings) GetTeamId() string {
	if o == nil || IsNil(o.TeamId) {
		var ret string
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTeamSettings) GetTeamIdOk() (*string, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *DtoTeamSettings) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given string and assigns it to the TeamId field.
func (o *DtoTeamSettings) SetTeamId(v string) {
	o.TeamId = &v
}

func (o DtoTeamSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoTeamSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contacts) {
		toSerialize["contacts"] = o.Contacts
	}
	if !IsNil(o.Subscriptions) {
		toSerialize["subscriptions"] = o.Subscriptions
	}
	if !IsNil(o.TeamId) {
		toSerialize["team_id"] = o.TeamId
	}
	return toSerialize, nil
}

type NullableDtoTeamSettings struct {
	value *DtoTeamSettings
	isSet bool
}

func (v NullableDtoTeamSettings) Get() *DtoTeamSettings {
	return v.value
}

func (v *NullableDtoTeamSettings) Set(val *DtoTeamSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoTeamSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoTeamSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoTeamSettings(val *DtoTeamSettings) *NullableDtoTeamSettings {
	return &NullableDtoTeamSettings{value: val, isSet: true}
}

func (v NullableDtoTeamSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoTeamSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
