/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the DtoTrigger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoTrigger{}

// DtoTrigger struct for DtoTrigger
type DtoTrigger struct {
	// A list of targets that have only alone metrics
	AloneMetrics map[string]bool `json:"alone_metrics,omitempty"`
	// Shows the exact cluster from where the metrics are fetched
	ClusterId *string `json:"cluster_id,omitempty"`
	// Datetime when the trigger was created
	CreatedAt NullableString `json:"created_at,omitempty"`
	// Username who created trigger
	CreatedBy *string `json:"created_by,omitempty"`
	// Description string
	Desc NullableString `json:"desc,omitempty"`
	// ERROR threshold
	ErrorValue NullableFloat32 `json:"error_value,omitempty"`
	// Used if you need more complex logic than provided by WARN/ERROR values
	Expression *string `json:"expression,omitempty"`
	// Trigger unique ID
	Id *string `json:"id,omitempty"`
	// Shows if trigger is remote (graphite-backend) based or stored inside Moira-Redis DB  Deprecated: Use TriggerSource field instead
	IsRemote *bool `json:"is_remote,omitempty"`
	// If true, first event NODATA → OK will be omitted
	MuteNewMetrics *bool `json:"mute_new_metrics,omitempty"`
	// Trigger name
	Name *string `json:"name,omitempty"`
	// Graphite patterns for trigger
	Patterns []string                  `json:"patterns,omitempty"`
	Sched    NullableMoiraScheduleData `json:"sched,omitempty"`
	// Set of tags to manipulate subscriptions
	Tags []string `json:"tags,omitempty"`
	// Graphite-like targets: t1, t2, ...
	Targets    []string `json:"targets,omitempty"`
	Throttling *int64   `json:"throttling,omitempty"`
	// Shows the type of source from where the metrics are fetched
	TriggerSource *string `json:"trigger_source,omitempty"`
	// Could be: rising, falling, expression
	TriggerType *string `json:"trigger_type,omitempty"`
	// When there are no metrics for trigger, Moira will switch metric to TTLState state after TTL seconds
	Ttl *int64 `json:"ttl,omitempty"`
	// When there are no metrics for trigger, Moira will switch metric to TTLState state after TTL seconds
	TtlState NullableString `json:"ttl_state,omitempty"`
	// Datetime  when the trigger was updated
	UpdatedAt NullableString `json:"updated_at,omitempty"`
	// Username who updated trigger
	UpdatedBy *string `json:"updated_by,omitempty"`
	// WARN threshold
	WarnValue NullableFloat32 `json:"warn_value,omitempty"`
}

// NewDtoTrigger instantiates a new DtoTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoTrigger() *DtoTrigger {
	this := DtoTrigger{}
	return &this
}

// NewDtoTriggerWithDefaults instantiates a new DtoTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoTriggerWithDefaults() *DtoTrigger {
	this := DtoTrigger{}
	return &this
}

// GetAloneMetrics returns the AloneMetrics field value if set, zero value otherwise.
func (o *DtoTrigger) GetAloneMetrics() map[string]bool {
	if o == nil || IsNil(o.AloneMetrics) {
		var ret map[string]bool
		return ret
	}
	return o.AloneMetrics
}

// GetAloneMetricsOk returns a tuple with the AloneMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetAloneMetricsOk() (map[string]bool, bool) {
	if o == nil || IsNil(o.AloneMetrics) {
		return map[string]bool{}, false
	}
	return o.AloneMetrics, true
}

// HasAloneMetrics returns a boolean if a field has been set.
func (o *DtoTrigger) HasAloneMetrics() bool {
	if o != nil && !IsNil(o.AloneMetrics) {
		return true
	}

	return false
}

// SetAloneMetrics gets a reference to the given map[string]bool and assigns it to the AloneMetrics field.
func (o *DtoTrigger) SetAloneMetrics(v map[string]bool) {
	o.AloneMetrics = v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *DtoTrigger) GetClusterId() string {
	if o == nil || IsNil(o.ClusterId) {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetClusterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *DtoTrigger) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *DtoTrigger) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DtoTrigger) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *DtoTrigger) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *DtoTrigger) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *DtoTrigger) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *DtoTrigger) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *DtoTrigger) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *DtoTrigger) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetDesc() string {
	if o == nil || IsNil(o.Desc.Get()) {
		var ret string
		return ret
	}
	return *o.Desc.Get()
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Desc.Get(), o.Desc.IsSet()
}

// HasDesc returns a boolean if a field has been set.
func (o *DtoTrigger) HasDesc() bool {
	if o != nil && o.Desc.IsSet() {
		return true
	}

	return false
}

// SetDesc gets a reference to the given NullableString and assigns it to the Desc field.
func (o *DtoTrigger) SetDesc(v string) {
	o.Desc.Set(&v)
}

// SetDescNil sets the value for Desc to be an explicit nil
func (o *DtoTrigger) SetDescNil() {
	o.Desc.Set(nil)
}

// UnsetDesc ensures that no value is present for Desc, not even an explicit nil
func (o *DtoTrigger) UnsetDesc() {
	o.Desc.Unset()
}

// GetErrorValue returns the ErrorValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetErrorValue() float32 {
	if o == nil || IsNil(o.ErrorValue.Get()) {
		var ret float32
		return ret
	}
	return *o.ErrorValue.Get()
}

// GetErrorValueOk returns a tuple with the ErrorValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetErrorValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorValue.Get(), o.ErrorValue.IsSet()
}

// HasErrorValue returns a boolean if a field has been set.
func (o *DtoTrigger) HasErrorValue() bool {
	if o != nil && o.ErrorValue.IsSet() {
		return true
	}

	return false
}

// SetErrorValue gets a reference to the given NullableFloat32 and assigns it to the ErrorValue field.
func (o *DtoTrigger) SetErrorValue(v float32) {
	o.ErrorValue.Set(&v)
}

// SetErrorValueNil sets the value for ErrorValue to be an explicit nil
func (o *DtoTrigger) SetErrorValueNil() {
	o.ErrorValue.Set(nil)
}

// UnsetErrorValue ensures that no value is present for ErrorValue, not even an explicit nil
func (o *DtoTrigger) UnsetErrorValue() {
	o.ErrorValue.Unset()
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *DtoTrigger) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *DtoTrigger) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *DtoTrigger) SetExpression(v string) {
	o.Expression = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoTrigger) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoTrigger) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoTrigger) SetId(v string) {
	o.Id = &v
}

// GetIsRemote returns the IsRemote field value if set, zero value otherwise.
func (o *DtoTrigger) GetIsRemote() bool {
	if o == nil || IsNil(o.IsRemote) {
		var ret bool
		return ret
	}
	return *o.IsRemote
}

// GetIsRemoteOk returns a tuple with the IsRemote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetIsRemoteOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRemote) {
		return nil, false
	}
	return o.IsRemote, true
}

// HasIsRemote returns a boolean if a field has been set.
func (o *DtoTrigger) HasIsRemote() bool {
	if o != nil && !IsNil(o.IsRemote) {
		return true
	}

	return false
}

// SetIsRemote gets a reference to the given bool and assigns it to the IsRemote field.
func (o *DtoTrigger) SetIsRemote(v bool) {
	o.IsRemote = &v
}

// GetMuteNewMetrics returns the MuteNewMetrics field value if set, zero value otherwise.
func (o *DtoTrigger) GetMuteNewMetrics() bool {
	if o == nil || IsNil(o.MuteNewMetrics) {
		var ret bool
		return ret
	}
	return *o.MuteNewMetrics
}

// GetMuteNewMetricsOk returns a tuple with the MuteNewMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetMuteNewMetricsOk() (*bool, bool) {
	if o == nil || IsNil(o.MuteNewMetrics) {
		return nil, false
	}
	return o.MuteNewMetrics, true
}

// HasMuteNewMetrics returns a boolean if a field has been set.
func (o *DtoTrigger) HasMuteNewMetrics() bool {
	if o != nil && !IsNil(o.MuteNewMetrics) {
		return true
	}

	return false
}

// SetMuteNewMetrics gets a reference to the given bool and assigns it to the MuteNewMetrics field.
func (o *DtoTrigger) SetMuteNewMetrics(v bool) {
	o.MuteNewMetrics = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DtoTrigger) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DtoTrigger) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DtoTrigger) SetName(v string) {
	o.Name = &v
}

// GetPatterns returns the Patterns field value if set, zero value otherwise.
func (o *DtoTrigger) GetPatterns() []string {
	if o == nil || IsNil(o.Patterns) {
		var ret []string
		return ret
	}
	return o.Patterns
}

// GetPatternsOk returns a tuple with the Patterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetPatternsOk() ([]string, bool) {
	if o == nil || IsNil(o.Patterns) {
		return nil, false
	}
	return o.Patterns, true
}

// HasPatterns returns a boolean if a field has been set.
func (o *DtoTrigger) HasPatterns() bool {
	if o != nil && !IsNil(o.Patterns) {
		return true
	}

	return false
}

// SetPatterns gets a reference to the given []string and assigns it to the Patterns field.
func (o *DtoTrigger) SetPatterns(v []string) {
	o.Patterns = v
}

// GetSched returns the Sched field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetSched() MoiraScheduleData {
	if o == nil || IsNil(o.Sched.Get()) {
		var ret MoiraScheduleData
		return ret
	}
	return *o.Sched.Get()
}

// GetSchedOk returns a tuple with the Sched field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetSchedOk() (*MoiraScheduleData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sched.Get(), o.Sched.IsSet()
}

// HasSched returns a boolean if a field has been set.
func (o *DtoTrigger) HasSched() bool {
	if o != nil && o.Sched.IsSet() {
		return true
	}

	return false
}

// SetSched gets a reference to the given NullableMoiraScheduleData and assigns it to the Sched field.
func (o *DtoTrigger) SetSched(v MoiraScheduleData) {
	o.Sched.Set(&v)
}

// SetSchedNil sets the value for Sched to be an explicit nil
func (o *DtoTrigger) SetSchedNil() {
	o.Sched.Set(nil)
}

// UnsetSched ensures that no value is present for Sched, not even an explicit nil
func (o *DtoTrigger) UnsetSched() {
	o.Sched.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *DtoTrigger) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *DtoTrigger) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *DtoTrigger) SetTags(v []string) {
	o.Tags = v
}

// GetTargets returns the Targets field value if set, zero value otherwise.
func (o *DtoTrigger) GetTargets() []string {
	if o == nil || IsNil(o.Targets) {
		var ret []string
		return ret
	}
	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetTargetsOk() ([]string, bool) {
	if o == nil || IsNil(o.Targets) {
		return nil, false
	}
	return o.Targets, true
}

// HasTargets returns a boolean if a field has been set.
func (o *DtoTrigger) HasTargets() bool {
	if o != nil && !IsNil(o.Targets) {
		return true
	}

	return false
}

// SetTargets gets a reference to the given []string and assigns it to the Targets field.
func (o *DtoTrigger) SetTargets(v []string) {
	o.Targets = v
}

// GetThrottling returns the Throttling field value if set, zero value otherwise.
func (o *DtoTrigger) GetThrottling() int64 {
	if o == nil || IsNil(o.Throttling) {
		var ret int64
		return ret
	}
	return *o.Throttling
}

// GetThrottlingOk returns a tuple with the Throttling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetThrottlingOk() (*int64, bool) {
	if o == nil || IsNil(o.Throttling) {
		return nil, false
	}
	return o.Throttling, true
}

// HasThrottling returns a boolean if a field has been set.
func (o *DtoTrigger) HasThrottling() bool {
	if o != nil && !IsNil(o.Throttling) {
		return true
	}

	return false
}

// SetThrottling gets a reference to the given int64 and assigns it to the Throttling field.
func (o *DtoTrigger) SetThrottling(v int64) {
	o.Throttling = &v
}

// GetTriggerSource returns the TriggerSource field value if set, zero value otherwise.
func (o *DtoTrigger) GetTriggerSource() string {
	if o == nil || IsNil(o.TriggerSource) {
		var ret string
		return ret
	}
	return *o.TriggerSource
}

// GetTriggerSourceOk returns a tuple with the TriggerSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetTriggerSourceOk() (*string, bool) {
	if o == nil || IsNil(o.TriggerSource) {
		return nil, false
	}
	return o.TriggerSource, true
}

// HasTriggerSource returns a boolean if a field has been set.
func (o *DtoTrigger) HasTriggerSource() bool {
	if o != nil && !IsNil(o.TriggerSource) {
		return true
	}

	return false
}

// SetTriggerSource gets a reference to the given string and assigns it to the TriggerSource field.
func (o *DtoTrigger) SetTriggerSource(v string) {
	o.TriggerSource = &v
}

// GetTriggerType returns the TriggerType field value if set, zero value otherwise.
func (o *DtoTrigger) GetTriggerType() string {
	if o == nil || IsNil(o.TriggerType) {
		var ret string
		return ret
	}
	return *o.TriggerType
}

// GetTriggerTypeOk returns a tuple with the TriggerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetTriggerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TriggerType) {
		return nil, false
	}
	return o.TriggerType, true
}

// HasTriggerType returns a boolean if a field has been set.
func (o *DtoTrigger) HasTriggerType() bool {
	if o != nil && !IsNil(o.TriggerType) {
		return true
	}

	return false
}

// SetTriggerType gets a reference to the given string and assigns it to the TriggerType field.
func (o *DtoTrigger) SetTriggerType(v string) {
	o.TriggerType = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *DtoTrigger) GetTtl() int64 {
	if o == nil || IsNil(o.Ttl) {
		var ret int64
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetTtlOk() (*int64, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *DtoTrigger) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int64 and assigns it to the Ttl field.
func (o *DtoTrigger) SetTtl(v int64) {
	o.Ttl = &v
}

// GetTtlState returns the TtlState field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetTtlState() string {
	if o == nil || IsNil(o.TtlState.Get()) {
		var ret string
		return ret
	}
	return *o.TtlState.Get()
}

// GetTtlStateOk returns a tuple with the TtlState field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetTtlStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TtlState.Get(), o.TtlState.IsSet()
}

// HasTtlState returns a boolean if a field has been set.
func (o *DtoTrigger) HasTtlState() bool {
	if o != nil && o.TtlState.IsSet() {
		return true
	}

	return false
}

// SetTtlState gets a reference to the given NullableString and assigns it to the TtlState field.
func (o *DtoTrigger) SetTtlState(v string) {
	o.TtlState.Set(&v)
}

// SetTtlStateNil sets the value for TtlState to be an explicit nil
func (o *DtoTrigger) SetTtlStateNil() {
	o.TtlState.Set(nil)
}

// UnsetTtlState ensures that no value is present for TtlState, not even an explicit nil
func (o *DtoTrigger) UnsetTtlState() {
	o.TtlState.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DtoTrigger) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableString and assigns it to the UpdatedAt field.
func (o *DtoTrigger) SetUpdatedAt(v string) {
	o.UpdatedAt.Set(&v)
}

// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *DtoTrigger) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *DtoTrigger) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *DtoTrigger) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTrigger) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *DtoTrigger) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *DtoTrigger) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

// GetWarnValue returns the WarnValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoTrigger) GetWarnValue() float32 {
	if o == nil || IsNil(o.WarnValue.Get()) {
		var ret float32
		return ret
	}
	return *o.WarnValue.Get()
}

// GetWarnValueOk returns a tuple with the WarnValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoTrigger) GetWarnValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarnValue.Get(), o.WarnValue.IsSet()
}

// HasWarnValue returns a boolean if a field has been set.
func (o *DtoTrigger) HasWarnValue() bool {
	if o != nil && o.WarnValue.IsSet() {
		return true
	}

	return false
}

// SetWarnValue gets a reference to the given NullableFloat32 and assigns it to the WarnValue field.
func (o *DtoTrigger) SetWarnValue(v float32) {
	o.WarnValue.Set(&v)
}

// SetWarnValueNil sets the value for WarnValue to be an explicit nil
func (o *DtoTrigger) SetWarnValueNil() {
	o.WarnValue.Set(nil)
}

// UnsetWarnValue ensures that no value is present for WarnValue, not even an explicit nil
func (o *DtoTrigger) UnsetWarnValue() {
	o.WarnValue.Unset()
}

func (o DtoTrigger) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoTrigger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AloneMetrics) {
		toSerialize["alone_metrics"] = o.AloneMetrics
	}
	if !IsNil(o.ClusterId) {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if o.Desc.IsSet() {
		toSerialize["desc"] = o.Desc.Get()
	}
	if o.ErrorValue.IsSet() {
		toSerialize["error_value"] = o.ErrorValue.Get()
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IsRemote) {
		toSerialize["is_remote"] = o.IsRemote
	}
	if !IsNil(o.MuteNewMetrics) {
		toSerialize["mute_new_metrics"] = o.MuteNewMetrics
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Patterns) {
		toSerialize["patterns"] = o.Patterns
	}
	if o.Sched.IsSet() {
		toSerialize["sched"] = o.Sched.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Targets) {
		toSerialize["targets"] = o.Targets
	}
	if !IsNil(o.Throttling) {
		toSerialize["throttling"] = o.Throttling
	}
	if !IsNil(o.TriggerSource) {
		toSerialize["trigger_source"] = o.TriggerSource
	}
	if !IsNil(o.TriggerType) {
		toSerialize["trigger_type"] = o.TriggerType
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if o.TtlState.IsSet() {
		toSerialize["ttl_state"] = o.TtlState.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	if o.WarnValue.IsSet() {
		toSerialize["warn_value"] = o.WarnValue.Get()
	}
	return toSerialize, nil
}

type NullableDtoTrigger struct {
	value *DtoTrigger
	isSet bool
}

func (v NullableDtoTrigger) Get() *DtoTrigger {
	return v.value
}

func (v *NullableDtoTrigger) Set(val *DtoTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoTrigger(val *DtoTrigger) *NullableDtoTrigger {
	return &NullableDtoTrigger{value: val, isSet: true}
}

func (v NullableDtoTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
