/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the DtoTeamMembers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoTeamMembers{}

// DtoTeamMembers struct for DtoTeamMembers
type DtoTeamMembers struct {
	Usernames []string `json:"usernames,omitempty"`
}

// NewDtoTeamMembers instantiates a new DtoTeamMembers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoTeamMembers() *DtoTeamMembers {
	this := DtoTeamMembers{}
	return &this
}

// NewDtoTeamMembersWithDefaults instantiates a new DtoTeamMembers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoTeamMembersWithDefaults() *DtoTeamMembers {
	this := DtoTeamMembers{}
	return &this
}

// GetUsernames returns the Usernames field value if set, zero value otherwise.
func (o *DtoTeamMembers) GetUsernames() []string {
	if o == nil || IsNil(o.Usernames) {
		var ret []string
		return ret
	}
	return o.Usernames
}

// GetUsernamesOk returns a tuple with the Usernames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoTeamMembers) GetUsernamesOk() ([]string, bool) {
	if o == nil || IsNil(o.Usernames) {
		return nil, false
	}
	return o.Usernames, true
}

// HasUsernames returns a boolean if a field has been set.
func (o *DtoTeamMembers) HasUsernames() bool {
	if o != nil && !IsNil(o.Usernames) {
		return true
	}

	return false
}

// SetUsernames gets a reference to the given []string and assigns it to the Usernames field.
func (o *DtoTeamMembers) SetUsernames(v []string) {
	o.Usernames = v
}

func (o DtoTeamMembers) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoTeamMembers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Usernames) {
		toSerialize["usernames"] = o.Usernames
	}
	return toSerialize, nil
}

type NullableDtoTeamMembers struct {
	value *DtoTeamMembers
	isSet bool
}

func (v NullableDtoTeamMembers) Get() *DtoTeamMembers {
	return v.value
}

func (v *NullableDtoTeamMembers) Set(val *DtoTeamMembers) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoTeamMembers) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoTeamMembers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoTeamMembers(val *DtoTeamMembers) *NullableDtoTeamMembers {
	return &NullableDtoTeamMembers{value: val, isSet: true}
}

func (v NullableDtoTeamMembers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoTeamMembers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
