/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the MoiraContactData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoiraContactData{}

// MoiraContactData struct for MoiraContactData
type MoiraContactData struct {
	Id    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Team  *string `json:"team,omitempty"`
	Type  *string `json:"type,omitempty"`
	User  *string `json:"user,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewMoiraContactData instantiates a new MoiraContactData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoiraContactData() *MoiraContactData {
	this := MoiraContactData{}
	return &this
}

// NewMoiraContactDataWithDefaults instantiates a new MoiraContactData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoiraContactDataWithDefaults() *MoiraContactData {
	this := MoiraContactData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MoiraContactData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoiraContactData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MoiraContactData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MoiraContactData) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MoiraContactData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoiraContactData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MoiraContactData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MoiraContactData) SetName(v string) {
	o.Name = &v
}

// GetTeam returns the Team field value if set, zero value otherwise.
func (o *MoiraContactData) GetTeam() string {
	if o == nil || IsNil(o.Team) {
		var ret string
		return ret
	}
	return *o.Team
}

// GetTeamOk returns a tuple with the Team field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoiraContactData) GetTeamOk() (*string, bool) {
	if o == nil || IsNil(o.Team) {
		return nil, false
	}
	return o.Team, true
}

// HasTeam returns a boolean if a field has been set.
func (o *MoiraContactData) HasTeam() bool {
	if o != nil && !IsNil(o.Team) {
		return true
	}

	return false
}

// SetTeam gets a reference to the given string and assigns it to the Team field.
func (o *MoiraContactData) SetTeam(v string) {
	o.Team = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MoiraContactData) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoiraContactData) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MoiraContactData) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MoiraContactData) SetType(v string) {
	o.Type = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *MoiraContactData) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoiraContactData) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *MoiraContactData) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *MoiraContactData) SetUser(v string) {
	o.User = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MoiraContactData) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoiraContactData) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MoiraContactData) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *MoiraContactData) SetValue(v string) {
	o.Value = &v
}

func (o MoiraContactData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoiraContactData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Team) {
		toSerialize["team"] = o.Team
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableMoiraContactData struct {
	value *MoiraContactData
	isSet bool
}

func (v NullableMoiraContactData) Get() *MoiraContactData {
	return v.value
}

func (v *NullableMoiraContactData) Set(val *MoiraContactData) {
	v.value = val
	v.isSet = true
}

func (v NullableMoiraContactData) IsSet() bool {
	return v.isSet
}

func (v *NullableMoiraContactData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoiraContactData(val *MoiraContactData) *NullableMoiraContactData {
	return &NullableMoiraContactData{value: val, isSet: true}
}

func (v NullableMoiraContactData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoiraContactData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
