/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the MoiraMaintenanceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoiraMaintenanceInfo{}

// MoiraMaintenanceInfo struct for MoiraMaintenanceInfo
type MoiraMaintenanceInfo struct {
	RemoveTime NullableInt64  `json:"remove_time,omitempty"`
	RemoveUser NullableString `json:"remove_user,omitempty"`
	SetupTime  NullableInt64  `json:"setup_time,omitempty"`
	SetupUser  NullableString `json:"setup_user,omitempty"`
}

// NewMoiraMaintenanceInfo instantiates a new MoiraMaintenanceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoiraMaintenanceInfo() *MoiraMaintenanceInfo {
	this := MoiraMaintenanceInfo{}
	return &this
}

// NewMoiraMaintenanceInfoWithDefaults instantiates a new MoiraMaintenanceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoiraMaintenanceInfoWithDefaults() *MoiraMaintenanceInfo {
	this := MoiraMaintenanceInfo{}
	return &this
}

// GetRemoveTime returns the RemoveTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MoiraMaintenanceInfo) GetRemoveTime() int64 {
	if o == nil || IsNil(o.RemoveTime.Get()) {
		var ret int64
		return ret
	}
	return *o.RemoveTime.Get()
}

// GetRemoveTimeOk returns a tuple with the RemoveTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MoiraMaintenanceInfo) GetRemoveTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoveTime.Get(), o.RemoveTime.IsSet()
}

// HasRemoveTime returns a boolean if a field has been set.
func (o *MoiraMaintenanceInfo) HasRemoveTime() bool {
	if o != nil && o.RemoveTime.IsSet() {
		return true
	}

	return false
}

// SetRemoveTime gets a reference to the given NullableInt64 and assigns it to the RemoveTime field.
func (o *MoiraMaintenanceInfo) SetRemoveTime(v int64) {
	o.RemoveTime.Set(&v)
}

// SetRemoveTimeNil sets the value for RemoveTime to be an explicit nil
func (o *MoiraMaintenanceInfo) SetRemoveTimeNil() {
	o.RemoveTime.Set(nil)
}

// UnsetRemoveTime ensures that no value is present for RemoveTime, not even an explicit nil
func (o *MoiraMaintenanceInfo) UnsetRemoveTime() {
	o.RemoveTime.Unset()
}

// GetRemoveUser returns the RemoveUser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MoiraMaintenanceInfo) GetRemoveUser() string {
	if o == nil || IsNil(o.RemoveUser.Get()) {
		var ret string
		return ret
	}
	return *o.RemoveUser.Get()
}

// GetRemoveUserOk returns a tuple with the RemoveUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MoiraMaintenanceInfo) GetRemoveUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoveUser.Get(), o.RemoveUser.IsSet()
}

// HasRemoveUser returns a boolean if a field has been set.
func (o *MoiraMaintenanceInfo) HasRemoveUser() bool {
	if o != nil && o.RemoveUser.IsSet() {
		return true
	}

	return false
}

// SetRemoveUser gets a reference to the given NullableString and assigns it to the RemoveUser field.
func (o *MoiraMaintenanceInfo) SetRemoveUser(v string) {
	o.RemoveUser.Set(&v)
}

// SetRemoveUserNil sets the value for RemoveUser to be an explicit nil
func (o *MoiraMaintenanceInfo) SetRemoveUserNil() {
	o.RemoveUser.Set(nil)
}

// UnsetRemoveUser ensures that no value is present for RemoveUser, not even an explicit nil
func (o *MoiraMaintenanceInfo) UnsetRemoveUser() {
	o.RemoveUser.Unset()
}

// GetSetupTime returns the SetupTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MoiraMaintenanceInfo) GetSetupTime() int64 {
	if o == nil || IsNil(o.SetupTime.Get()) {
		var ret int64
		return ret
	}
	return *o.SetupTime.Get()
}

// GetSetupTimeOk returns a tuple with the SetupTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MoiraMaintenanceInfo) GetSetupTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SetupTime.Get(), o.SetupTime.IsSet()
}

// HasSetupTime returns a boolean if a field has been set.
func (o *MoiraMaintenanceInfo) HasSetupTime() bool {
	if o != nil && o.SetupTime.IsSet() {
		return true
	}

	return false
}

// SetSetupTime gets a reference to the given NullableInt64 and assigns it to the SetupTime field.
func (o *MoiraMaintenanceInfo) SetSetupTime(v int64) {
	o.SetupTime.Set(&v)
}

// SetSetupTimeNil sets the value for SetupTime to be an explicit nil
func (o *MoiraMaintenanceInfo) SetSetupTimeNil() {
	o.SetupTime.Set(nil)
}

// UnsetSetupTime ensures that no value is present for SetupTime, not even an explicit nil
func (o *MoiraMaintenanceInfo) UnsetSetupTime() {
	o.SetupTime.Unset()
}

// GetSetupUser returns the SetupUser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MoiraMaintenanceInfo) GetSetupUser() string {
	if o == nil || IsNil(o.SetupUser.Get()) {
		var ret string
		return ret
	}
	return *o.SetupUser.Get()
}

// GetSetupUserOk returns a tuple with the SetupUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MoiraMaintenanceInfo) GetSetupUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SetupUser.Get(), o.SetupUser.IsSet()
}

// HasSetupUser returns a boolean if a field has been set.
func (o *MoiraMaintenanceInfo) HasSetupUser() bool {
	if o != nil && o.SetupUser.IsSet() {
		return true
	}

	return false
}

// SetSetupUser gets a reference to the given NullableString and assigns it to the SetupUser field.
func (o *MoiraMaintenanceInfo) SetSetupUser(v string) {
	o.SetupUser.Set(&v)
}

// SetSetupUserNil sets the value for SetupUser to be an explicit nil
func (o *MoiraMaintenanceInfo) SetSetupUserNil() {
	o.SetupUser.Set(nil)
}

// UnsetSetupUser ensures that no value is present for SetupUser, not even an explicit nil
func (o *MoiraMaintenanceInfo) UnsetSetupUser() {
	o.SetupUser.Unset()
}

func (o MoiraMaintenanceInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoiraMaintenanceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RemoveTime.IsSet() {
		toSerialize["remove_time"] = o.RemoveTime.Get()
	}
	if o.RemoveUser.IsSet() {
		toSerialize["remove_user"] = o.RemoveUser.Get()
	}
	if o.SetupTime.IsSet() {
		toSerialize["setup_time"] = o.SetupTime.Get()
	}
	if o.SetupUser.IsSet() {
		toSerialize["setup_user"] = o.SetupUser.Get()
	}
	return toSerialize, nil
}

type NullableMoiraMaintenanceInfo struct {
	value *MoiraMaintenanceInfo
	isSet bool
}

func (v NullableMoiraMaintenanceInfo) Get() *MoiraMaintenanceInfo {
	return v.value
}

func (v *NullableMoiraMaintenanceInfo) Set(val *MoiraMaintenanceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMoiraMaintenanceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMoiraMaintenanceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoiraMaintenanceInfo(val *MoiraMaintenanceInfo) *NullableMoiraMaintenanceInfo {
	return &NullableMoiraMaintenanceInfo{value: val, isSet: true}
}

func (v NullableMoiraMaintenanceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoiraMaintenanceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
