/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the DtoSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoSubscription{}

// DtoSubscription struct for DtoSubscription
type DtoSubscription struct {
	AnyTags           *bool                     `json:"any_tags,omitempty"`
	Contacts          []string                  `json:"contacts,omitempty"`
	Enabled           *bool                     `json:"enabled,omitempty"`
	Id                *string                   `json:"id,omitempty"`
	IgnoreRecoverings *bool                     `json:"ignore_recoverings,omitempty"`
	IgnoreWarnings    *bool                     `json:"ignore_warnings,omitempty"`
	Plotting          *MoiraPlottingData        `json:"plotting,omitempty"`
	Sched             NullableMoiraScheduleData `json:"sched,omitempty"`
	Tags              []string                  `json:"tags,omitempty"`
	TeamId            *string                   `json:"team_id,omitempty"`
	Throttling        *bool                     `json:"throttling,omitempty"`
	User              *string                   `json:"user,omitempty"`
}

// NewDtoSubscription instantiates a new DtoSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoSubscription() *DtoSubscription {
	this := DtoSubscription{}
	return &this
}

// NewDtoSubscriptionWithDefaults instantiates a new DtoSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoSubscriptionWithDefaults() *DtoSubscription {
	this := DtoSubscription{}
	return &this
}

// GetAnyTags returns the AnyTags field value if set, zero value otherwise.
func (o *DtoSubscription) GetAnyTags() bool {
	if o == nil || IsNil(o.AnyTags) {
		var ret bool
		return ret
	}
	return *o.AnyTags
}

// GetAnyTagsOk returns a tuple with the AnyTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetAnyTagsOk() (*bool, bool) {
	if o == nil || IsNil(o.AnyTags) {
		return nil, false
	}
	return o.AnyTags, true
}

// HasAnyTags returns a boolean if a field has been set.
func (o *DtoSubscription) HasAnyTags() bool {
	if o != nil && !IsNil(o.AnyTags) {
		return true
	}

	return false
}

// SetAnyTags gets a reference to the given bool and assigns it to the AnyTags field.
func (o *DtoSubscription) SetAnyTags(v bool) {
	o.AnyTags = &v
}

// GetContacts returns the Contacts field value if set, zero value otherwise.
func (o *DtoSubscription) GetContacts() []string {
	if o == nil || IsNil(o.Contacts) {
		var ret []string
		return ret
	}
	return o.Contacts
}

// GetContactsOk returns a tuple with the Contacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetContactsOk() ([]string, bool) {
	if o == nil || IsNil(o.Contacts) {
		return nil, false
	}
	return o.Contacts, true
}

// HasContacts returns a boolean if a field has been set.
func (o *DtoSubscription) HasContacts() bool {
	if o != nil && !IsNil(o.Contacts) {
		return true
	}

	return false
}

// SetContacts gets a reference to the given []string and assigns it to the Contacts field.
func (o *DtoSubscription) SetContacts(v []string) {
	o.Contacts = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *DtoSubscription) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *DtoSubscription) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *DtoSubscription) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoSubscription) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoSubscription) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoSubscription) SetId(v string) {
	o.Id = &v
}

// GetIgnoreRecoverings returns the IgnoreRecoverings field value if set, zero value otherwise.
func (o *DtoSubscription) GetIgnoreRecoverings() bool {
	if o == nil || IsNil(o.IgnoreRecoverings) {
		var ret bool
		return ret
	}
	return *o.IgnoreRecoverings
}

// GetIgnoreRecoveringsOk returns a tuple with the IgnoreRecoverings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetIgnoreRecoveringsOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreRecoverings) {
		return nil, false
	}
	return o.IgnoreRecoverings, true
}

// HasIgnoreRecoverings returns a boolean if a field has been set.
func (o *DtoSubscription) HasIgnoreRecoverings() bool {
	if o != nil && !IsNil(o.IgnoreRecoverings) {
		return true
	}

	return false
}

// SetIgnoreRecoverings gets a reference to the given bool and assigns it to the IgnoreRecoverings field.
func (o *DtoSubscription) SetIgnoreRecoverings(v bool) {
	o.IgnoreRecoverings = &v
}

// GetIgnoreWarnings returns the IgnoreWarnings field value if set, zero value otherwise.
func (o *DtoSubscription) GetIgnoreWarnings() bool {
	if o == nil || IsNil(o.IgnoreWarnings) {
		var ret bool
		return ret
	}
	return *o.IgnoreWarnings
}

// GetIgnoreWarningsOk returns a tuple with the IgnoreWarnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetIgnoreWarningsOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreWarnings) {
		return nil, false
	}
	return o.IgnoreWarnings, true
}

// HasIgnoreWarnings returns a boolean if a field has been set.
func (o *DtoSubscription) HasIgnoreWarnings() bool {
	if o != nil && !IsNil(o.IgnoreWarnings) {
		return true
	}

	return false
}

// SetIgnoreWarnings gets a reference to the given bool and assigns it to the IgnoreWarnings field.
func (o *DtoSubscription) SetIgnoreWarnings(v bool) {
	o.IgnoreWarnings = &v
}

// GetPlotting returns the Plotting field value if set, zero value otherwise.
func (o *DtoSubscription) GetPlotting() MoiraPlottingData {
	if o == nil || IsNil(o.Plotting) {
		var ret MoiraPlottingData
		return ret
	}
	return *o.Plotting
}

// GetPlottingOk returns a tuple with the Plotting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetPlottingOk() (*MoiraPlottingData, bool) {
	if o == nil || IsNil(o.Plotting) {
		return nil, false
	}
	return o.Plotting, true
}

// HasPlotting returns a boolean if a field has been set.
func (o *DtoSubscription) HasPlotting() bool {
	if o != nil && !IsNil(o.Plotting) {
		return true
	}

	return false
}

// SetPlotting gets a reference to the given MoiraPlottingData and assigns it to the Plotting field.
func (o *DtoSubscription) SetPlotting(v MoiraPlottingData) {
	o.Plotting = &v
}

// GetSched returns the Sched field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DtoSubscription) GetSched() MoiraScheduleData {
	if o == nil || IsNil(o.Sched.Get()) {
		var ret MoiraScheduleData
		return ret
	}
	return *o.Sched.Get()
}

// GetSchedOk returns a tuple with the Sched field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DtoSubscription) GetSchedOk() (*MoiraScheduleData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sched.Get(), o.Sched.IsSet()
}

// HasSched returns a boolean if a field has been set.
func (o *DtoSubscription) HasSched() bool {
	if o != nil && o.Sched.IsSet() {
		return true
	}

	return false
}

// SetSched gets a reference to the given NullableMoiraScheduleData and assigns it to the Sched field.
func (o *DtoSubscription) SetSched(v MoiraScheduleData) {
	o.Sched.Set(&v)
}

// SetSchedNil sets the value for Sched to be an explicit nil
func (o *DtoSubscription) SetSchedNil() {
	o.Sched.Set(nil)
}

// UnsetSched ensures that no value is present for Sched, not even an explicit nil
func (o *DtoSubscription) UnsetSched() {
	o.Sched.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *DtoSubscription) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *DtoSubscription) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *DtoSubscription) SetTags(v []string) {
	o.Tags = v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *DtoSubscription) GetTeamId() string {
	if o == nil || IsNil(o.TeamId) {
		var ret string
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetTeamIdOk() (*string, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *DtoSubscription) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given string and assigns it to the TeamId field.
func (o *DtoSubscription) SetTeamId(v string) {
	o.TeamId = &v
}

// GetThrottling returns the Throttling field value if set, zero value otherwise.
func (o *DtoSubscription) GetThrottling() bool {
	if o == nil || IsNil(o.Throttling) {
		var ret bool
		return ret
	}
	return *o.Throttling
}

// GetThrottlingOk returns a tuple with the Throttling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetThrottlingOk() (*bool, bool) {
	if o == nil || IsNil(o.Throttling) {
		return nil, false
	}
	return o.Throttling, true
}

// HasThrottling returns a boolean if a field has been set.
func (o *DtoSubscription) HasThrottling() bool {
	if o != nil && !IsNil(o.Throttling) {
		return true
	}

	return false
}

// SetThrottling gets a reference to the given bool and assigns it to the Throttling field.
func (o *DtoSubscription) SetThrottling(v bool) {
	o.Throttling = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *DtoSubscription) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSubscription) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *DtoSubscription) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *DtoSubscription) SetUser(v string) {
	o.User = &v
}

func (o DtoSubscription) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnyTags) {
		toSerialize["any_tags"] = o.AnyTags
	}
	if !IsNil(o.Contacts) {
		toSerialize["contacts"] = o.Contacts
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IgnoreRecoverings) {
		toSerialize["ignore_recoverings"] = o.IgnoreRecoverings
	}
	if !IsNil(o.IgnoreWarnings) {
		toSerialize["ignore_warnings"] = o.IgnoreWarnings
	}
	if !IsNil(o.Plotting) {
		toSerialize["plotting"] = o.Plotting
	}
	if o.Sched.IsSet() {
		toSerialize["sched"] = o.Sched.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.TeamId) {
		toSerialize["team_id"] = o.TeamId
	}
	if !IsNil(o.Throttling) {
		toSerialize["throttling"] = o.Throttling
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableDtoSubscription struct {
	value *DtoSubscription
	isSet bool
}

func (v NullableDtoSubscription) Get() *DtoSubscription {
	return v.value
}

func (v *NullableDtoSubscription) Set(val *DtoSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoSubscription(val *DtoSubscription) *NullableDtoSubscription {
	return &NullableDtoSubscription{value: val, isSet: true}
}

func (v NullableDtoSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
