/*
Moira Alert

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: master
Contact: kontur.moira.alert@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg

import (
	"encoding/json"
)

// checks if the DtoSaveTriggerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoSaveTriggerResponse{}

// DtoSaveTriggerResponse struct for DtoSaveTriggerResponse
type DtoSaveTriggerResponse struct {
	CheckResult *DtoTriggerCheckResponse `json:"checkResult,omitempty"`
	Id          *string                  `json:"id,omitempty"`
	Message     *string                  `json:"message,omitempty"`
}

// NewDtoSaveTriggerResponse instantiates a new DtoSaveTriggerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoSaveTriggerResponse() *DtoSaveTriggerResponse {
	this := DtoSaveTriggerResponse{}
	return &this
}

// NewDtoSaveTriggerResponseWithDefaults instantiates a new DtoSaveTriggerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoSaveTriggerResponseWithDefaults() *DtoSaveTriggerResponse {
	this := DtoSaveTriggerResponse{}
	return &this
}

// GetCheckResult returns the CheckResult field value if set, zero value otherwise.
func (o *DtoSaveTriggerResponse) GetCheckResult() DtoTriggerCheckResponse {
	if o == nil || IsNil(o.CheckResult) {
		var ret DtoTriggerCheckResponse
		return ret
	}
	return *o.CheckResult
}

// GetCheckResultOk returns a tuple with the CheckResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSaveTriggerResponse) GetCheckResultOk() (*DtoTriggerCheckResponse, bool) {
	if o == nil || IsNil(o.CheckResult) {
		return nil, false
	}
	return o.CheckResult, true
}

// HasCheckResult returns a boolean if a field has been set.
func (o *DtoSaveTriggerResponse) HasCheckResult() bool {
	if o != nil && !IsNil(o.CheckResult) {
		return true
	}

	return false
}

// SetCheckResult gets a reference to the given DtoTriggerCheckResponse and assigns it to the CheckResult field.
func (o *DtoSaveTriggerResponse) SetCheckResult(v DtoTriggerCheckResponse) {
	o.CheckResult = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DtoSaveTriggerResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSaveTriggerResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DtoSaveTriggerResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DtoSaveTriggerResponse) SetId(v string) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DtoSaveTriggerResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoSaveTriggerResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DtoSaveTriggerResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DtoSaveTriggerResponse) SetMessage(v string) {
	o.Message = &v
}

func (o DtoSaveTriggerResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoSaveTriggerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckResult) {
		toSerialize["checkResult"] = o.CheckResult
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDtoSaveTriggerResponse struct {
	value *DtoSaveTriggerResponse
	isSet bool
}

func (v NullableDtoSaveTriggerResponse) Get() *DtoSaveTriggerResponse {
	return v.value
}

func (v *NullableDtoSaveTriggerResponse) Set(val *DtoSaveTriggerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoSaveTriggerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoSaveTriggerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoSaveTriggerResponse(val *DtoSaveTriggerResponse) *NullableDtoSaveTriggerResponse {
	return &NullableDtoSaveTriggerResponse{value: val, isSet: true}
}

func (v NullableDtoSaveTriggerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoSaveTriggerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
