// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePagerParams creates a new DeletePagerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePagerParams() *DeletePagerParams {
	return &DeletePagerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePagerParamsWithTimeout creates a new DeletePagerParams object
// with the ability to set a timeout on a request.
func NewDeletePagerParamsWithTimeout(timeout time.Duration) *DeletePagerParams {
	return &DeletePagerParams{
		timeout: timeout,
	}
}

// NewDeletePagerParamsWithContext creates a new DeletePagerParams object
// with the ability to set a context for a request.
func NewDeletePagerParamsWithContext(ctx context.Context) *DeletePagerParams {
	return &DeletePagerParams{
		Context: ctx,
	}
}

// NewDeletePagerParamsWithHTTPClient creates a new DeletePagerParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePagerParamsWithHTTPClient(client *http.Client) *DeletePagerParams {
	return &DeletePagerParams{
		HTTPClient: client,
	}
}

/*
DeletePagerParams contains all the parameters to send to the API endpoint

	for the delete pager operation.

	Typically these are written to a http.Request.
*/
type DeletePagerParams struct {

	/* PagerID.

	   Pager ID

	   Default: "bcba82f5-48cf-44c0-b7d6-e1d32c64a88c"
	*/
	PagerID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete pager params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePagerParams) WithDefaults() *DeletePagerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete pager params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePagerParams) SetDefaults() {
	var (
		pagerIDDefault = string("bcba82f5-48cf-44c0-b7d6-e1d32c64a88c")
	)

	val := DeletePagerParams{
		PagerID: &pagerIDDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the delete pager params
func (o *DeletePagerParams) WithTimeout(timeout time.Duration) *DeletePagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete pager params
func (o *DeletePagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete pager params
func (o *DeletePagerParams) WithContext(ctx context.Context) *DeletePagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete pager params
func (o *DeletePagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete pager params
func (o *DeletePagerParams) WithHTTPClient(client *http.Client) *DeletePagerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete pager params
func (o *DeletePagerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPagerID adds the pagerID to the delete pager params
func (o *DeletePagerParams) WithPagerID(pagerID *string) *DeletePagerParams {
	o.SetPagerID(pagerID)
	return o
}

// SetPagerID adds the pagerId to the delete pager params
func (o *DeletePagerParams) SetPagerID(pagerID *string) {
	o.PagerID = pagerID
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PagerID != nil {

		// query param pagerID
		var qrPagerID string

		if o.PagerID != nil {
			qrPagerID = *o.PagerID
		}
		qPagerID := qrPagerID
		if qPagerID != "" {

			if err := r.SetQueryParam("pagerID", qPagerID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
