// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTriggerStateParams creates a new GetTriggerStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTriggerStateParams() *GetTriggerStateParams {
	return &GetTriggerStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTriggerStateParamsWithTimeout creates a new GetTriggerStateParams object
// with the ability to set a timeout on a request.
func NewGetTriggerStateParamsWithTimeout(timeout time.Duration) *GetTriggerStateParams {
	return &GetTriggerStateParams{
		timeout: timeout,
	}
}

// NewGetTriggerStateParamsWithContext creates a new GetTriggerStateParams object
// with the ability to set a context for a request.
func NewGetTriggerStateParamsWithContext(ctx context.Context) *GetTriggerStateParams {
	return &GetTriggerStateParams{
		Context: ctx,
	}
}

// NewGetTriggerStateParamsWithHTTPClient creates a new GetTriggerStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTriggerStateParamsWithHTTPClient(client *http.Client) *GetTriggerStateParams {
	return &GetTriggerStateParams{
		HTTPClient: client,
	}
}

/*
GetTriggerStateParams contains all the parameters to send to the API endpoint

	for the get trigger state operation.

	Typically these are written to a http.Request.
*/
type GetTriggerStateParams struct {

	/* TriggerID.

	   Trigger ID

	   Default: "bcba82f5-48cf-44c0-b7d6-e1d32c64a88c"
	*/
	TriggerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get trigger state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTriggerStateParams) WithDefaults() *GetTriggerStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get trigger state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTriggerStateParams) SetDefaults() {
	var (
		triggerIDDefault = string("bcba82f5-48cf-44c0-b7d6-e1d32c64a88c")
	)

	val := GetTriggerStateParams{
		TriggerID: triggerIDDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get trigger state params
func (o *GetTriggerStateParams) WithTimeout(timeout time.Duration) *GetTriggerStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get trigger state params
func (o *GetTriggerStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get trigger state params
func (o *GetTriggerStateParams) WithContext(ctx context.Context) *GetTriggerStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get trigger state params
func (o *GetTriggerStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get trigger state params
func (o *GetTriggerStateParams) WithHTTPClient(client *http.Client) *GetTriggerStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get trigger state params
func (o *GetTriggerStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTriggerID adds the triggerID to the get trigger state params
func (o *GetTriggerStateParams) WithTriggerID(triggerID string) *GetTriggerStateParams {
	o.SetTriggerID(triggerID)
	return o
}

// SetTriggerID adds the triggerId to the get trigger state params
func (o *GetTriggerStateParams) SetTriggerID(triggerID string) {
	o.TriggerID = triggerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTriggerStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param triggerID
	if err := r.SetPathParam("triggerID", o.TriggerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
