// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// GetTriggersNoisinessReader is a Reader for the GetTriggersNoisiness structure.
type GetTriggersNoisinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTriggersNoisinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTriggersNoisinessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTriggersNoisinessBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetTriggersNoisinessUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTriggersNoisinessInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /trigger/noisiness] get-triggers-noisiness", response, response.Code())
	}
}

// NewGetTriggersNoisinessOK creates a GetTriggersNoisinessOK with default headers values
func NewGetTriggersNoisinessOK() *GetTriggersNoisinessOK {
	return &GetTriggersNoisinessOK{}
}

/*
GetTriggersNoisinessOK describes a response with status code 200, with default header values.

Get noisiness for triggers in range
*/
type GetTriggersNoisinessOK struct {
	Payload *models.DtoTriggerNoisinessList
}

// IsSuccess returns true when this get triggers noisiness o k response has a 2xx status code
func (o *GetTriggersNoisinessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get triggers noisiness o k response has a 3xx status code
func (o *GetTriggersNoisinessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get triggers noisiness o k response has a 4xx status code
func (o *GetTriggersNoisinessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get triggers noisiness o k response has a 5xx status code
func (o *GetTriggersNoisinessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get triggers noisiness o k response a status code equal to that given
func (o *GetTriggersNoisinessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get triggers noisiness o k response
func (o *GetTriggersNoisinessOK) Code() int {
	return 200
}

func (o *GetTriggersNoisinessOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessOK %s", 200, payload)
}

func (o *GetTriggersNoisinessOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessOK %s", 200, payload)
}

func (o *GetTriggersNoisinessOK) GetPayload() *models.DtoTriggerNoisinessList {
	return o.Payload
}

func (o *GetTriggersNoisinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtoTriggerNoisinessList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTriggersNoisinessBadRequest creates a GetTriggersNoisinessBadRequest with default headers values
func NewGetTriggersNoisinessBadRequest() *GetTriggersNoisinessBadRequest {
	return &GetTriggersNoisinessBadRequest{}
}

/*
GetTriggersNoisinessBadRequest describes a response with status code 400, with default header values.

Bad request from client
*/
type GetTriggersNoisinessBadRequest struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this get triggers noisiness bad request response has a 2xx status code
func (o *GetTriggersNoisinessBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get triggers noisiness bad request response has a 3xx status code
func (o *GetTriggersNoisinessBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get triggers noisiness bad request response has a 4xx status code
func (o *GetTriggersNoisinessBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get triggers noisiness bad request response has a 5xx status code
func (o *GetTriggersNoisinessBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get triggers noisiness bad request response a status code equal to that given
func (o *GetTriggersNoisinessBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get triggers noisiness bad request response
func (o *GetTriggersNoisinessBadRequest) Code() int {
	return 400
}

func (o *GetTriggersNoisinessBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessBadRequest %s", 400, payload)
}

func (o *GetTriggersNoisinessBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessBadRequest %s", 400, payload)
}

func (o *GetTriggersNoisinessBadRequest) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetTriggersNoisinessBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTriggersNoisinessUnprocessableEntity creates a GetTriggersNoisinessUnprocessableEntity with default headers values
func NewGetTriggersNoisinessUnprocessableEntity() *GetTriggersNoisinessUnprocessableEntity {
	return &GetTriggersNoisinessUnprocessableEntity{}
}

/*
GetTriggersNoisinessUnprocessableEntity describes a response with status code 422, with default header values.

Render error
*/
type GetTriggersNoisinessUnprocessableEntity struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this get triggers noisiness unprocessable entity response has a 2xx status code
func (o *GetTriggersNoisinessUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get triggers noisiness unprocessable entity response has a 3xx status code
func (o *GetTriggersNoisinessUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get triggers noisiness unprocessable entity response has a 4xx status code
func (o *GetTriggersNoisinessUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get triggers noisiness unprocessable entity response has a 5xx status code
func (o *GetTriggersNoisinessUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get triggers noisiness unprocessable entity response a status code equal to that given
func (o *GetTriggersNoisinessUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get triggers noisiness unprocessable entity response
func (o *GetTriggersNoisinessUnprocessableEntity) Code() int {
	return 422
}

func (o *GetTriggersNoisinessUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessUnprocessableEntity %s", 422, payload)
}

func (o *GetTriggersNoisinessUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessUnprocessableEntity %s", 422, payload)
}

func (o *GetTriggersNoisinessUnprocessableEntity) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetTriggersNoisinessUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTriggersNoisinessInternalServerError creates a GetTriggersNoisinessInternalServerError with default headers values
func NewGetTriggersNoisinessInternalServerError() *GetTriggersNoisinessInternalServerError {
	return &GetTriggersNoisinessInternalServerError{}
}

/*
GetTriggersNoisinessInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetTriggersNoisinessInternalServerError struct {
	Payload *models.APIErrorResponse
}

// IsSuccess returns true when this get triggers noisiness internal server error response has a 2xx status code
func (o *GetTriggersNoisinessInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get triggers noisiness internal server error response has a 3xx status code
func (o *GetTriggersNoisinessInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get triggers noisiness internal server error response has a 4xx status code
func (o *GetTriggersNoisinessInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get triggers noisiness internal server error response has a 5xx status code
func (o *GetTriggersNoisinessInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get triggers noisiness internal server error response a status code equal to that given
func (o *GetTriggersNoisinessInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get triggers noisiness internal server error response
func (o *GetTriggersNoisinessInternalServerError) Code() int {
	return 500
}

func (o *GetTriggersNoisinessInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessInternalServerError %s", 500, payload)
}

func (o *GetTriggersNoisinessInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trigger/noisiness][%d] getTriggersNoisinessInternalServerError %s", 500, payload)
}

func (o *GetTriggersNoisinessInternalServerError) GetPayload() *models.APIErrorResponse {
	return o.Payload
}

func (o *GetTriggersNoisinessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
