// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/moira-alert/client-go/pkg/models"
)

// RemoveTriggerReader is a Reader for the RemoveTrigger structure.
type RemoveTriggerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveTriggerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveTriggerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRemoveTriggerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveTriggerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /trigger/{triggerID}] remove-trigger", response, response.Code())
	}
}

// NewRemoveTriggerOK creates a RemoveTriggerOK with default headers values
func NewRemoveTriggerOK() *RemoveTriggerOK {
	return &RemoveTriggerOK{}
}

/*
RemoveTriggerOK describes a response with status code 200, with default header values.

Successfully removed
*/
type RemoveTriggerOK struct {
}

// IsSuccess returns true when this remove trigger o k response has a 2xx status code
func (o *RemoveTriggerOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove trigger o k response has a 3xx status code
func (o *RemoveTriggerOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove trigger o k response has a 4xx status code
func (o *RemoveTriggerOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove trigger o k response has a 5xx status code
func (o *RemoveTriggerOK) IsServerError() bool {
	return false
}

// IsCode returns true when this remove trigger o k response a status code equal to that given
func (o *RemoveTriggerOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the remove trigger o k response
func (o *RemoveTriggerOK) Code() int {
	return 200
}

func (o *RemoveTriggerOK) Error() string {
	return fmt.Sprintf("[DELETE /trigger/{triggerID}][%d] removeTriggerOK", 200)
}

func (o *RemoveTriggerOK) String() string {
	return fmt.Sprintf("[DELETE /trigger/{triggerID}][%d] removeTriggerOK", 200)
}

func (o *RemoveTriggerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveTriggerNotFound creates a RemoveTriggerNotFound with default headers values
func NewRemoveTriggerNotFound() *RemoveTriggerNotFound {
	return &RemoveTriggerNotFound{}
}

/*
RemoveTriggerNotFound describes a response with status code 404, with default header values.

Resource not found
*/
type RemoveTriggerNotFound struct {
	Payload *models.APIErrorNotFoundExample
}

// IsSuccess returns true when this remove trigger not found response has a 2xx status code
func (o *RemoveTriggerNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove trigger not found response has a 3xx status code
func (o *RemoveTriggerNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove trigger not found response has a 4xx status code
func (o *RemoveTriggerNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove trigger not found response has a 5xx status code
func (o *RemoveTriggerNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this remove trigger not found response a status code equal to that given
func (o *RemoveTriggerNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the remove trigger not found response
func (o *RemoveTriggerNotFound) Code() int {
	return 404
}

func (o *RemoveTriggerNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /trigger/{triggerID}][%d] removeTriggerNotFound %s", 404, payload)
}

func (o *RemoveTriggerNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /trigger/{triggerID}][%d] removeTriggerNotFound %s", 404, payload)
}

func (o *RemoveTriggerNotFound) GetPayload() *models.APIErrorNotFoundExample {
	return o.Payload
}

func (o *RemoveTriggerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorNotFoundExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveTriggerInternalServerError creates a RemoveTriggerInternalServerError with default headers values
func NewRemoveTriggerInternalServerError() *RemoveTriggerInternalServerError {
	return &RemoveTriggerInternalServerError{}
}

/*
RemoveTriggerInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type RemoveTriggerInternalServerError struct {
	Payload *models.APIErrorInternalServerExample
}

// IsSuccess returns true when this remove trigger internal server error response has a 2xx status code
func (o *RemoveTriggerInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove trigger internal server error response has a 3xx status code
func (o *RemoveTriggerInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove trigger internal server error response has a 4xx status code
func (o *RemoveTriggerInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove trigger internal server error response has a 5xx status code
func (o *RemoveTriggerInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this remove trigger internal server error response a status code equal to that given
func (o *RemoveTriggerInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the remove trigger internal server error response
func (o *RemoveTriggerInternalServerError) Code() int {
	return 500
}

func (o *RemoveTriggerInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /trigger/{triggerID}][%d] removeTriggerInternalServerError %s", 500, payload)
}

func (o *RemoveTriggerInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /trigger/{triggerID}][%d] removeTriggerInternalServerError %s", 500, payload)
}

func (o *RemoveTriggerInternalServerError) GetPayload() *models.APIErrorInternalServerExample {
	return o.Payload
}

func (o *RemoveTriggerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorInternalServerExample)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
